In [1]:
%load_ext autoreload
%autoreload 2

In [39]:
from sqlalchemy import create_engine, MetaData,Table,Column, Integer, String,text,select
from sqlalchemy.orm import Session
from sqlalchemy.orm import DeclarativeBase

from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column

from sqlalchemy import and_
from sqlalchemy import func,desc,asc
from sqlalchemy import cast, Numeric,Float

from datetime import date

import pandas as pd
pd.options.display.float_format = '{:.4f}'.format
pd.options.display.max_columns = None
pd.set_option('display.max_rows', 50)
import urllib.parse

import os
import sys
sys.path.append(os.path.abspath('../alpha_vantage_api/'))
from alpha_vantage_api import query_all_statements,read_api_key

import numpy as np
import time

In [3]:
read_api_key()

'N0YVA5RVTIR2D1OL'

In [4]:
with open("db_password.txt") as file:
    db_pw = file.read()

db_pw = db_pw.strip()

In [5]:
# Encode that '@' symbol!
encoded_pw = urllib.parse.quote_plus(db_pw)
url = f"postgresql://postgres:{encoded_pw}@localhost:5432/postgres"

### First step using sqlalchemy

In [6]:
engine = create_engine(url)

## ORM way

In [7]:
# declarative base class
class Base(DeclarativeBase):
    pass

# Load the "Parent" first
class BalanceSheet(Base):
    __tablename__ = "balance_sheet"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

# Then load the "Children"
class IncomeStatement(Base):
    __tablename__ = "income_statement"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class CashFlow(Base):
    __tablename__ = "cash_flow"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class SharesOutstanding(Base):
    __tablename__ = "shares_outstanding"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Splits(Base):
    __tablename__ = "splits"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Dividends(Base):
    __tablename__ = "dividends"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Earnings(Base):
    __tablename__ = "earnings"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class EarningsEstimates(Base):
    __tablename__ = "earnings_estimates"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Overview(Base):
    __tablename__ = "overview"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Stock(Base):
    __tablename__ = "stock"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Currency(Base):
    __tablename__ = "currency"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class OHLCV(Base):
    __tablename__ = "ohlcv"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

In [40]:
def write_to_postgres(df,tablename,stock_id,engine,schema_name,column_mapping=None):
    #df = pd.read_csv(path)
    df["stock_id"] = stock_id
    # Check if column_mapping is a dictionary and not empty
    if isinstance(column_mapping, dict) and column_mapping:
        df.rename(columns=column_mapping, inplace=True)
    df.drop("Unnamed: 0",axis=1,inplace=True, errors='ignore')
    df.to_sql(name=tablename,
              con=engine, 
              schema=schema_name,
              if_exists="append",
              index=False)

In [10]:
def get_stock_id(model, engine, ticker):
    stmt = select(model.stock_id).where(model.ticker == ticker)
    return pd.read_sql(stmt, engine).iloc[0, 0]

In [17]:
earnings_column_mapping = {"stock_id": "stock_id",
                           "fiscalDateEnding": "fiscal_date_ending",
                           "reportedEPS": "reported_eps"}

In [11]:
balance_sheet_mapping = {
    'fiscalDateEnding': 'fiscal_date_ending',
    'reportedCurrency': 'reported_currency',
    'totalAssets': 'total_assets',
    'totalCurrentAssets': 'total_current_assets',
    'cashAndCashEquivalentsAtCarryingValue': 'cash_and_cash_equivalents_at_carrying_value',
    'cashAndShortTermInvestments': 'cash_and_short_term_investments',
    'inventory': 'inventory',
    'currentNetReceivables': 'current_net_receivables',
    'totalNonCurrentAssets': 'total_non_current_assets',
    'propertyPlantEquipment': 'property_plant_equipment',
    'accumulatedDepreciationAmortizationPPE': 'accumulated_depreciation_amortization_ppe',
    'intangibleAssets': 'intangible_assets',
    'intangibleAssetsExcludingGoodwill': 'intangible_assets_excluding_goodwill',
    'goodwill': 'goodwill',
    'investments': 'investments',
    'longTermInvestments': 'long_term_investments',
    'shortTermInvestments': 'short_term_investments',
    'otherCurrentAssets': 'other_current_assets',
    'otherNonCurrentAssets': 'other_non_current_assets',
    'totalLiabilities': 'total_liabilities',
    'totalCurrentLiabilities': 'total_current_liabilities',
    'currentAccountsPayable': 'current_accounts_payable',
    'deferredRevenue': 'deferred_revenue',
    'currentDebt': 'current_debt',
    'shortTermDebt': 'short_term_debt',
    'totalNonCurrentLiabilities': 'total_non_current_liabilities',
    'capitalLeaseObligations': 'capital_lease_obligations',
    'longTermDebt': 'long_term_debt',
    'currentLongTermDebt': 'current_long_term_debt',
    'longTermDebtNoncurrent': 'long_term_debt_noncurrent',
    'shortLongTermDebtTotal': 'short_long_term_debt_total',
    'otherCurrentLiabilities': 'other_current_liabilities',
    'otherNonCurrentLiabilities': 'other_non_current_liabilities',
    'totalShareholderEquity': 'total_shareholder_equity',
    'treasuryStock': 'treasury_stock',
    'retainedEarnings': 'retained_earnings',
    'commonStock': 'common_stock',
    'commonStockSharesOutstanding': 'common_stock_shares_outstanding',
    'stock_id': 'stock_id'
}

In [12]:
income_column_mapping = {
    'fiscalDateEnding': 'fiscal_date_ending',
    'reportedCurrency': 'reported_currency',
    'grossProfit': 'gross_profit',
    'totalRevenue': 'total_revenue',
    'costOfRevenue': 'cost_of_revenue',
    'costofGoodsAndServicesSold': 'cost_of_goods_and_services_sold',
    'operatingIncome': 'operating_income',
    'sellingGeneralAndAdministrative': 'selling_general_and_administrative',
    'researchAndDevelopment': 'research_and_development',
    'operatingExpenses': 'operating_expenses',
    'investmentIncomeNet': 'investment_income_net',
    'netInterestIncome': 'net_interest_income',
    'interestIncome': 'interest_income',
    'interestExpense': 'interest_expense',
    'nonInterestIncome': 'non_interest_income',
    'otherNonOperatingIncome': 'other_non_operating_income',
    'depreciation': 'depreciation',
    'depreciationAndAmortization': 'depreciation_and_amortization',
    'incomeBeforeTax': 'income_before_tax',
    'incomeTaxExpense': 'income_tax_expense',
    'interestAndDebtExpense': 'interest_and_debt_expense',
    'netIncomeFromContinuingOperations': 'net_income_from_continuing_operations',
    'comprehensiveIncomeNetOfTax': 'comprehensive_income_net_of_tax',
    'ebit': 'ebit',
    'ebitda': 'ebitda',
    'netIncome': 'net_income',
    'stock_id': 'stock_id'
}

In [13]:
cash_flow_mapping = {
    'fiscalDateEnding': 'fiscal_date_ending',
    'reportedCurrency': 'reported_currency',
    'operatingCashflow': 'operating_cashflow',
    'paymentsForOperatingActivities': 'payments_for_operating_activities',
    'proceedsFromOperatingActivities': 'proceeds_from_operating_activities',
    'changeInOperatingLiabilities': 'change_in_operating_liabilities',
    'changeInOperatingAssets': 'change_in_operating_assets',
    'depreciationDepletionAndAmortization': 'depreciation_depletion_and_amortization',
    'capitalExpenditures': 'capital_expenditures',
    'changeInReceivables': 'change_in_receivables',
    'changeInInventory': 'change_in_inventory',
    'profitLoss': 'profit_loss',
    'cashflowFromInvestment': 'cashflow_from_investment',
    'cashflowFromFinancing': 'cashflow_from_financing',
    'proceedsFromRepaymentsOfShortTermDebt': 'proceeds_from_repayments_of_short_term_debt',
    'paymentsForRepurchaseOfCommonStock': 'payments_for_repurchase_of_common_stock',
    'paymentsForRepurchaseOfEquity': 'payments_for_repurchase_of_equity',
    'paymentsForRepurchaseOfPreferredStock': 'payments_for_repurchase_of_preferred_stock',
    'dividendPayout': 'dividend_payout',
    'dividendPayoutCommonStock': 'dividend_payout_common_stock',
    'dividendPayoutPreferredStock': 'dividend_payout_preferred_stock',
    'proceedsFromIssuanceOfCommonStock': 'proceeds_from_issuance_of_common_stock',
    'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet': 'proceeds_from_issuance_of_long_term_debt_and_capital_securities',
    'proceedsFromIssuanceOfPreferredStock': 'proceeds_from_issuance_of_preferred_stock',
    'proceedsFromRepurchaseOfEquity': 'proceeds_from_repurchase_of_equity',
    'proceedsFromSaleOfTreasuryStock': 'proceeds_from_sale_of_treasury_stock',
    'stockBasedCompensation': 'stock_based_compensation',
    'changeInCashAndCashEquivalents': 'change_in_cash_and_cash_equivalents',
    'changeInExchangeRate': 'change_in_exchange_rate',
    'netIncome': 'net_income',
    'stock_id': 'stock_id'
}

In [14]:
overview_mapping ={
                    "stock_id": "stock_id",
                    "AssetType": "asset_type",
                    "Name": "name",
                    "Description": "description",
                    "CIK": "cik",
                    "Exchange": "exchange",
                    "Currency": "currency_id",
                    "Country": "country",
                    "Sector": "sector",
                    "Industry": "industry",
                    "Address": "address",
                    "OfficialSite": "official_site",
                    "FiscalYearEnd": "fiscal_year_end",
                    "LatestQuarter": "latest_quarter",
                    "MarketCapitalization": "market_capitalization",
                    "EBITDA": "ebitda",
                    "PERatio": "pe_ratio",
                    "PEGRatio": "peg_ratio",
                    "BookValue": "book_value",
                    "DividendPerShare": "dividend_per_share",
                    "DividendYield": "dividend_yield",
                    "EPS": "eps",
                    "RevenuePerShareTTM": "revenue_per_share_ttm",
                    "ProfitMargin": "profit_margin",
                    "OperatingMarginTTM": "operating_margin_ttm",
                    "ReturnOnAssetsTTM": "return_on_assets_ttm",
                    "ReturnOnEquityTTM": "return_on_equity_ttm",
                    "RevenueTTM": "revenue_ttm",
                    "GrossProfitTTM": "gross_profit_ttm",
                    "DilutedEPSTTM": "diluted_eps_ttm",
                    "QuarterlyEarningsGrowthYOY": "quarterly_earnings_growth_yoy",
                    "QuarterlyRevenueGrowthYOY": "quarterly_revenue_growth_yoy",
                    "AnalystTargetPrice": "analyst_target_price",
                    "AnalystRatingStrongBuy": "analyst_rating_strong_buy",
                    "AnalystRatingBuy": "analyst_rating_buy",
                    "AnalystRatingHold": "analyst_rating_hold",
                    "AnalystRatingSell": "analyst_rating_sell",
                    "AnalystRatingStrongSell": "analyst_rating_strong_sell",
                    "TrailingPE": "trailing_pe",
                    "ForwardPE": "forward_pe",
                    "PriceToSalesRatioTTM": "price_to_sales_ratio_ttm",
                    "PriceToBookRatio": "price_to_book_ratio",
                    "EVToRevenue": "ev_to_revenue",
                    "EVToEBITDA": "ev_to_ebitda",
                    "Beta": "beta",
                    "52WeekHigh": "high_52_week",
                    "52WeekLow": "low_52_week",
                    "50DayMovingAverage": "moving_average_50_day",
                    "200DayMovingAverage": "moving_average_200_day",
                    "SharesOutstanding": "shares_outstanding",
                    "SharesFloat": "shares_float",
                    "PercentInsiders": "percent_insiders",
                    "PercentInstitutions": "percent_institutions",
                    "DividendDate": "dividend_date",
                    "ExDividendDate": "ex_dividend_date"
                }

In [34]:
function_names= {   "BALANCE_SHEET":"EMPTY",
                    "INCOME_STATEMENT":"EMPTY",
                    "CASH_FLOW":"EMPTY",
                    "OVERVIEW":"EMPTY",
                    "DIVIDENDS":"data",
                    "SPLITS":"data",
                    "SHARES_OUTSTANDING":"data",
                    "EARNINGS":"annualEarnings",
                    "EARNINGS_ESTIMATES":"estimates"
                    }

mapping_names= {    "BALANCE_SHEET":balance_sheet_mapping,
                    "INCOME_STATEMENT":income_column_mapping,
                    "CASH_FLOW":cash_flow_mapping,
                    "OVERVIEW":overview_mapping,
                    "DIVIDENDS":None,
                    "SPLITS":None,
                    "SHARES_OUTSTANDING":None,
                    "EARNINGS":earnings_column_mapping,
                    "EARNINGS_ESTIMATES":None
                    }

table_names= {      "BALANCE_SHEET":"balance_sheet",
                    "INCOME_STATEMENT":"income_statement",
                    "CASH_FLOW":"cash_flow",
                    "OVERVIEW": "overview",
                    "DIVIDENDS":"dividends",
                    "SPLITS":"splits",
                    "SHARES_OUTSTANDING":"shares_outstanding",
                    "EARNINGS":"earnings",
                    "EARNINGS_ESTIMATES":"earnings_estimates"
                    }

class_names= {      "BALANCE_SHEET":BalanceSheet,
                    "INCOME_STATEMENT":IncomeStatement,
                    "CASH_FLOW":CashFlow,
                    "OVERVIEW": Overview,
                    "DIVIDENDS": Dividends,
                    "SPLITS": Splits,
                    "SHARES_OUTSTANDING":SharesOutstanding,
                    "EARNINGS":Earnings,
                    "EARNINGS_ESTIMATES":EarningsEstimates
                    }

In [23]:
sp87_tickers = [
    "ABBV", "ADBE", "AEP", "AIG", "AMGN", "ATVI", 
    "AXP", "BA", "BAC", "BMY", "BRK.B", "C", "CAT", "CHTR", "CL", "CMCSA", 
    "COF", "COP", "COST", "CRM", "CSCO", "CVS", "CVX", "DE", "DFS", "DHR", 
    "DIS", "DOW", "DUK", "EMR", "EXC", "F", "FDX", "GD", "GE", "GILD", 
    "GM", "GOOGL", "GS", "HD", "HON", "INTU", "ISRG", 
    "JNJ", "JPM", "KHC", "KO", "LIN", "LLY", "LMT", "LOW", "LRCX", "MA", 
    "MCD", "MDLZ", "MDT", "MMM", "MO", "MRK", "MS", "MU", 
    "NEE", "NFLX", "NKE", "ORCL", "OXY", "PEP", "PFE", "PG", "PM", 
    "PYPL", "QCOM", "RAY", "RTX", "SBUX", "SCHW", "SO", "SPG", "T", "TGT", 
    "TMO", "TMUS", "TXN", "UNH", "UNP", "UPS", "USB", "V", "VZ", 
    "WFC", "WMT", "XOM"
]

### Add new stock_id into postgres

In [37]:
from sqlalchemy import insert

ticker = sp87_tickers[2]
stmt = insert(Stock).values(ticker=ticker)

with engine.connect() as conn:
    result = conn.execute(stmt)
    conn.commit()

In [38]:
schema_name = "alpha_vantage_db"
stock_id = get_stock_id(Stock, engine,ticker) #get from postgres
for mapping in mapping_names:
    dict_to_pass = {mapping: function_names[mapping]}
    df = query_all_statements(ticker,dict_to_pass)
    time.sleep(15)
    df = df.replace('None', np.nan).where(pd.notnull(df), None)
    tablename = table_names[mapping]
    if mapping == "OVERVIEW":
        df.drop(columns=['Symbol'],inplace=True)
        df.loc[0,'Currency']='1'
        df['Currency'] = df['Currency'].astype('int64')
        write_to_postgres(df,tablename, stock_id, engine, schema_name,mapping_names[mapping])
    elif mapping == "BALANCE_SHEET" or mapping == "CASH_FLOW" or mapping == "INCOME_STATEMENT":
        annual_df = pd.DataFrame(df["annualReports"].iloc[0])
        annual_df = annual_df.assign(report_type = "ANNUAL")
        annual_df = annual_df.replace('None', np.nan).where(pd.notnull(annual_df), None)
        write_to_postgres(annual_df,tablename, stock_id, engine, schema_name,mapping_names[mapping])
        quarterly_df = pd.DataFrame(df["quarterlyReports"].iloc[0])
        quarterly_df = quarterly_df.assign(report_type = "QUARTERLY")
        quarterly_df = quarterly_df.replace('None', np.nan).where(pd.notnull(quarterly_df), None)
        write_to_postgres(quarterly_df,tablename, stock_id, engine, schema_name,mapping_names[mapping])
    else:
        write_to_postgres(df,tablename, stock_id, engine, schema_name,mapping_names[mapping])

key is BALANCE_SHEET
key is INCOME_STATEMENT
key is CASH_FLOW
key is OVERVIEW, value is EMPTY
⚠️ API Limit hit on DIVIDENDS. Skipping...

UnboundLocalError: cannot access local variable 'df' where it is not associated with a value

In [70]:
df

,fiscal_date_ending,reported_currency,operating_cashflow,payments_for_operating_activities,proceeds_from_operating_activities,change_in_operating_liabilities,change_in_operating_assets,depreciation_depletion_and_amortization,capital_expenditures,change_in_receivables,change_in_inventory,profit_loss,cashflow_from_investment,cashflow_from_financing,proceeds_from_repayments_of_short_term_debt,payments_for_repurchase_of_common_stock,payments_for_repurchase_of_equity,payments_for_repurchase_of_preferred_stock,dividend_payout,dividend_payout_common_stock,dividend_payout_preferred_stock,proceeds_from_issuance_of_common_stock,proceeds_from_issuance_of_long_term_debt_and_capital_securities,proceeds_from_issuance_of_preferred_stock,proceeds_from_repurchase_of_equity,proceeds_from_sale_of_treasury_stock,stock_based_compensation,change_in_cash_and_cash_equivalents,change_in_exchange_rate,net_income,report_type,stock_id
0,2026-01-31,USD,8260000000,NaN,NaN,NaN,NaN,2153000000,250000000,NaN,-692000000,NaN,-115000000,-10149000000,NaN,NaN,NaN,NaN,3086000000,3086000000,NaN,NaN,NaN,NaN,-7850000000,NaN,2176000000,NaN,NaN,7349000000,QUARTERLY,12
1,2025-10-31,USD,7703000000,NaN,NaN,NaN,NaN,2233000000,237000000,NaN,-90000000,NaN,-367000000,-1876000000,NaN,NaN,NaN,NaN,2797000000,2797000000,NaN,NaN,NaN,NaN,0,NaN,2195000000,NaN,NaN,8518000000,QUARTERLY,12
2,2025-07-31,USD,7166000000,NaN,NaN,NaN,NaN,2202000000,142000000,NaN,-163000000,NaN,94000000,-6014000000,NaN,NaN,NaN,NaN,2786000000,2786000000,NaN,NaN,NaN,NaN,-58000000,NaN,2322000000,NaN,NaN,4140000000,QUARTERLY,12
3,2025-04-30,USD,6555000000,NaN,NaN,NaN,NaN,2166000000,144000000,NaN,-109000000,NaN,-133000000,-6257000000,NaN,NaN,NaN,NaN,2785000000,2785000000,NaN,NaN,NaN,NaN,-4216000000,NaN,1771000000,NaN,NaN,4965000000,QUARTERLY,12
4,2025-01-31,USD,6113000000,NaN,NaN,NaN,NaN,2174000000,100000000,NaN,-148000000,NaN,-174000000,-5980000000,NaN,NaN,NaN,NaN,2774000000,2774000000,NaN,NaN,NaN,NaN,-2036000000,NaN,1280000000,NaN,NaN,5503000000,QUARTERLY,12
5,2024-10-31,USD,5604000000,NaN,NaN,NaN,NaN,2611000000,122000000,NaN,134000000,NaN,-132000000,-6076000000,NaN,NaN,NaN,NaN,2484000000,2484000000,NaN,NaN,NaN,NaN,-1204000000,NaN,1314000000,NaN,NaN,4324000000,QUARTERLY,12
6,2024-07-31,USD,4963000000,NaN,NaN,NaN,NaN,2524000000,172000000,NaN,-52000000,NaN,3245000000,-8065000000,NaN,NaN,NaN,NaN,2452000000,2452000000,NaN,NaN,NaN,NaN,-1350000000,NaN,1388000000,NaN,NaN,-1875000000,QUARTERLY,12
7,2024-04-30,USD,4580000000,NaN,NaN,NaN,NaN,2530000000,132000000,NaN,82000000,NaN,-706000000,-5929000000,NaN,NaN,NaN,NaN,2443000000,2443000000,NaN,NaN,NaN,NaN,-1548000000,NaN,1457000000,NaN,NaN,2121000000,QUARTERLY,12
8,2024-01-31,USD,4815000000,NaN,NaN,NaN,NaN,2345000000,122000000,NaN,-14000000,NaN,-25477000000,18337000000,NaN,NaN,NaN,NaN,2435000000,2435000000,NaN,NaN,NaN,NaN,-8290000000,NaN,1582000000,NaN,NaN,1274000000,QUARTERLY,12
9,2023-10-31,USD,4828000000,NaN,NaN,NaN,NaN,932000000,105000000,NaN,-56000000,NaN,-124000000,-2570000000,NaN,NaN,NaN,NaN,1904000000,1904000000,NaN,NaN,NaN,NaN,-577000000,NaN,638000000,NaN,NaN,3524000000,QUARTERLY,12
10,2023-07-31,USD,4719000000,NaN,NaN,NaN,NaN,932000000,122000000,135000000,44000000,NaN,-144000000,-4073000000,NaN,NaN,NaN,NaN,1901000000,1901000000,NaN,NaN,NaN,NaN,-2167000000,NaN,629000000,502000000,NaN,3303000000,QUARTERLY,12
11,2023-04-30,USD,4502000000,NaN,NaN,NaN,NaN,939000000,122000000,185000000,13000000,NaN,-318000000,-5278000000,NaN,NaN,NaN,NaN,1914000000,1914000000,NaN,NaN,NaN,NaN,-3420000000,NaN,513000000,-1094000000,NaN,3481000000,QUARTERLY,12
12,2023-01-31,USD,4036000000,NaN,NaN,NaN,NaN,1032000000,103000000,-276000000,26000000,NaN,-103000000,-3702000000,NaN,NaN,NaN,NaN,1926000000,1926000000,NaN,NaN,NaN,NaN,-1521000000,NaN,391000000,231000000,NaN,3774000000,QUARTERLY,12
13,2022-10-31,USD,4583000000,NaN,NaN,NaN,NaN,1216000000,122000000,-241000000,-87000000,NaN,-128000000,-2016000000,NaN,NaN,NaN,NaN,1782000000,1782000000,NaN,NaN,NaN,NaN,-274000000,NaN,387000000,2439000000,NaN,3359000000,QUARTERLY,12
14,2022-07-31,USD,4424000000,NaN,NaN,NaN,NaN,1217000000,116000000,375000000,-170000000,NaN,80000000,-3532000000,NaN,NaN,NaN,NaN,1736000000,1736000000,NaN,NaN,NaN,NaN,-1792000000,NaN,373000000,972000000,NaN,3074000000,QUARTERLY,12
15,2022-04-30,USD,4243000000,NaN,NaN,NaN,NaN,1264000000,85000000,-536000000,-147000000,NaN,-310000000,-5147000000,NaN,NaN,NaN,NaN,1750000000,1750000000,NaN,NaN,NaN,NaN,-3290000000,NaN,386000000,-1214000000,NaN,2590000000,QUARTERLY,12
16,2022-01-31,USD,3486000000,NaN,NaN,NaN,NaN,1287000000,101000000,-468000000,-223000000,NaN,-309000000,-5121000000,NaN,NaN,NaN,NaN,1764000000,1764000000,NaN,NaN,NaN,NaN,-3099000000,NaN,387000000,-1944000000,NaN,2472000000,QUARTERLY,12
17,2021-10-31,USD,3541000000,NaN,NaN,NaN,NaN,1501000000,88000000,160000000,-137000000,NaN,50000000,-2533000000,NaN,NaN,NaN,NaN,1561000000,1561000000,NaN,NaN,NaN,NaN,-266000000,NaN,414000000,1058000000,NaN,1989000000,QUARTERLY,12
18,2021-07-31,USD,3541000000,NaN,NaN,NaN,NaN,1503000000,115000000,191000000,-156000000,NaN,-47000000,-1907000000,NaN,NaN,NaN,NaN,1556000000,1556000000,NaN,NaN,NaN,NaN,-347000000,NaN,421000000,1587000000,NaN,1876000000,QUARTERLY,12
19,2021-04-30,USD,3569000000,NaN,NaN,NaN,NaN,1504000000,126000000,106000000,-52000000,NaN,-126000000,-3477000000,NaN,NaN,NaN,NaN,1552000000,1552000000,NaN,NaN,NaN,NaN,-461000000,NaN,425000000,-34000000,NaN,1493000000,QUARTERLY,12
20,2021-01-31,USD,3113000000,NaN,NaN,NaN,NaN,1533000000,114000000,-247000000,51000000,NaN,-122000000,-1057000000,NaN,NaN,NaN,NaN,1543000000,1543000000,NaN,NaN,NaN,NaN,-225000000,NaN,444000000,1934000000,NaN,1378000000,QUARTERLY,12
21,2020-10-31,USD,3348000000,NaN,NaN,NaN,NaN,1728000000,102000000,NaN,67000000,NaN,-100000000,-4487000000,NaN,NaN,NaN,NaN,1395000000,1395000000,NaN,NaN,NaN,NaN,-185000000,NaN,449000000,NaN,NaN,1324000000,QUARTERLY,12
22,2020-07-31,USD,3178000000,NaN,NaN,NaN,NaN,1719000000,105000000,542000000,-128000000,NaN,-46000000,-3482000000,NaN,NaN,NaN,NaN,1386000000,1386000000,NaN,NaN,NaN,NaN,-192000000,NaN,465000000,-350000000,NaN,688000000,QUARTERLY,12
23,2020-04-30,USD,3213000000,NaN,NaN,NaN,NaN,1730000000,148000000,440000000,-10000000,NaN,24000000,-474000000,NaN,NaN,NaN,NaN,1381000000,1381000000,NaN,NaN,NaN,NaN,-219000000,NaN,517000000,2763000000,NaN,563000000,QUARTERLY,12
24,2020-01-31,USD,2322000000,NaN,NaN,NaN,NaN,1728000000,108000000,-392000000,40000000,NaN,-10987000000,10054000000,NaN,NaN,NaN,NaN,1372000000,1372000000,NaN,NaN,NaN,NaN,-169000000,NaN,545000000,1389000000,NaN,385000000,QUARTERLY,12
25,2019-10-31,USD,2479000000,NaN,NaN,NaN,NaN,1452000000,96000000,285000000,217000000,NaN,-88000000,-2798000000,NaN,NaN,NaN,NaN,1054000000,1054000000,NaN,NaN,NaN,NaN,-587000000,NaN,544000000,-407000000,NaN,847000000,QUARTERLY,12
26,2019-07-31,USD,2419000000,NaN,NaN,NaN,NaN,1450000000,112000000,-60000000,-57000000,NaN,-35000000,-2250000000,NaN,NaN,NaN,NaN,1057000000,1057000000,NaN,NaN,NaN,NaN,-977000000,NaN,632000000,134000000,NaN,715000000,QUARTERLY,12
27,2019-04-30,USD,2667000000,NaN,NaN,NaN,NaN,1447000000,125000000,193000000,40000000,NaN,-106000000,-2326000000,NaN,NaN,NaN,NaN,1057000000,1057000000,NaN,NaN,NaN,NaN,-1330000000,NaN,544000000,235000000,NaN,691000000,QUARTERLY,12
28,2019-01-31,USD,2132000000,NaN,NaN,NaN,NaN,1459000000,99000000,68000000,50000000,NaN,-15193000000,13862000000,NaN,NaN,NaN,NaN,1067000000,1067000000,NaN,NaN,NaN,NaN,-3513000000,NaN,465000000,801000000,NaN,471000000,QUARTERLY,12
29,2018-10-31,USD,2635000000,NaN,NaN,NaN,NaN,968000000,106000000,NaN,92000000,NaN,-118000000,-2361000000,NaN,NaN,NaN,NaN,723000000,723000000,NaN,NaN,NaN,NaN,-1533000000,NaN,317000000,NaN,NaN,1115000000,QUARTERLY,12
30,2018-07-31,USD,2247000000,NaN,NaN,NaN,NaN,965000000,120000000,NaN,19000000,NaN,-174000000,-6124000000,NaN,NaN,NaN,NaN,754000000,754000000,NaN,NaN,NaN,NaN,-5411000000,NaN,315000000,NaN,NaN,1196000000,QUARTERLY,12
31,2018-04-30,USD,2313000000,NaN,NaN,NaN,NaN,964000000,189000000,NaN,56000000,NaN,-155000000,-1047000000,NaN,NaN,NaN,NaN,766000000,766000000,NaN,NaN,NaN,NaN,-347000000,NaN,296000000,NaN,NaN,3733000000,QUARTERLY,12
32,2018-01-31,USD,1685000000,NaN,NaN,NaN,NaN,1184000000,220000000,NaN,250000000,NaN,-4227000000,-1586000000,NaN,NaN,NaN,NaN,755000000,755000000,NaN,NaN,NaN,NaN,34000000,NaN,299000000,NaN,NaN,6566000000,QUARTERLY,12
33,2017-10-31,USD,1959000000,NaN,NaN,NaN,NaN,1219000000,233000000,NaN,-16000000,NaN,396000000,3600000000,NaN,NaN,NaN,NaN,439000000,439000000,NaN,NaN,NaN,NaN,3980000000,NaN,252000000,NaN,NaN,671000000,QUARTERLY,12
34,2017-07-31,USD,1656000000,NaN,NaN,NaN,NaN,1211000000,255000000,NaN,-119000000,NaN,-258000000,-403000000,NaN,NaN,NaN,NaN,438000000,438000000,NaN,NaN,NaN,NaN,41000000,NaN,251000000,NaN,NaN,507000000,QUARTERLY,12
35,2017-04-30,USD,1583000000,NaN,NaN,NaN,NaN,1193000000,256000000,NaN,31000000,NaN,-493000000,-372000000,NaN,NaN,NaN,NaN,437000000,437000000,NaN,NaN,NaN,NaN,89000000,NaN,216000000,NaN,NaN,464000000,QUARTERLY,12
36,2017-01-31,USD,1353000000,NaN,NaN,NaN,NaN,1114000000,325000000,NaN,65000000,NaN,-319000000,-595000000,NaN,NaN,NaN,NaN,431000000,431000000,NaN,NaN,NaN,NaN,13550000000,NaN,202000000,NaN,NaN,252000000,QUARTERLY,12
37,2016-10-31,USD,1352000000,NaN,NaN,NaN,NaN,700000000,193000000,NaN,-92000000,NaN,26000000,-242000000,NaN,NaN,NaN,NaN,202000000,202000000,NaN,NaN,NaN,NaN,3584000000,NaN,205000000,NaN,NaN,-668000000,QUARTERLY,12
38,2016-07-31,USD,963000000,NaN,NaN,NaN,NaN,1058000000,232000000,NaN,168000000,NaN,426000000,-1469000000,NaN,NaN,NaN,NaN,199000000,199000000,NaN,NaN,NaN,NaN,38000000,NaN,219000000,NaN,NaN,-315000000,QUARTERLY,12
39,2016-04-30,USD,622000000,NaN,NaN,NaN,NaN,1040000000,158000000,NaN,886000000,NaN,-10207000000,9457000000,NaN,NaN,NaN,NaN,204000000,204000000,NaN,NaN,NaN,NaN,15926000000,NaN,198000000,NaN,NaN,-1255000000,QUARTERLY,12
40,2016-01-31,USD,474000000,NaN,NaN,NaN,NaN,244000000,140000000,NaN,34000000,NaN,-85000000,-42000000,NaN,NaN,NaN,NaN,122000000,122000000,NaN,NaN,NaN,NaN,NaN,NaN,57000000,NaN,NaN,377000000,QUARTERLY,12
41,2015-10-31,USD,582000000,NaN,NaN,NaN,NaN,250000000,106000000,NaN,-1000000,NaN,-64000000,-50000000,NaN,NaN,NaN,NaN,116000000,116000000,NaN,NaN,NaN,NaN,241000000,NaN,63000000,NaN,NaN,429000000,QUARTERLY,12
42,2015-07-31,USD,592000000,NaN,NaN,NaN,NaN,256000000,148000000,NaN,20000000,NaN,-542000000,-1204000000,NaN,NaN,NaN,NaN,104000000,104000000,NaN,NaN,NaN,NaN,NaN,NaN,63000000,NaN,NaN,240000000,QUARTERLY,12
43,2015-04-30,USD,663000000,NaN,NaN,NaN,NaN,230000000,177000000,NaN,10000000,NaN,-149000000,-575000000,NaN,NaN,NaN,NaN,99000000,99000000,NaN,NaN,NaN,NaN,NaN,NaN,57000000,NaN,NaN,344000000,QUARTERLY,12
44,2015-01-31,USD,481000000,NaN,NaN,NaN,NaN,226000000,162000000,NaN,33000000,NaN,514000000,-30000000,NaN,NaN,NaN,NaN,89000000,89000000,NaN,NaN,NaN,NaN,NaN,NaN,49000000,NaN,NaN,351000000,QUARTERLY,12
45,2014-10-31,USD,381000000,NaN,NaN,NaN,NaN,250000000,189000000,NaN,-6000000,NaN,-35000000,-19000000,NaN,NaN,NaN,NaN,81000000,81000000,NaN,NaN,NaN,NaN,124000000,NaN,54000000,NaN,NaN,117000000,QUARTERLY,12
46,2014-07-31,USD,314000000,NaN,NaN,NaN,NaN,257000000,95000000,NaN,215000000,NaN,-5739000000,5424000000,NaN,NaN,NaN,NaN,73000000,73000000,NaN,NaN,NaN,NaN,5600000000,NaN,55000000,NaN,NaN,-164000000,QUARTERLY,12
47,2014-04-30,USD,251000000,NaN,NaN,NaN,NaN,61000000,73000000,NaN,-15000000,NaN,-59000000,-26000000,NaN,NaN,NaN,NaN,68000000,68000000,NaN,NaN,NaN,NaN,NaN,NaN,30000000,NaN,NaN,158000000,QUARTERLY,12
48,2014-01-31,USD,229000000,NaN,NaN,NaN,NaN,57000000,52000000,NaN,-1000000,NaN,-52000000,-50000000,NaN,NaN,NaN,NaN,62000000,62000000,NaN,NaN,NaN,NaN,-12000000,NaN,24000000,NaN,NaN,134000000,QUARTERLY,12
49,2013-10-31,USD,209000000,NaN,NaN,NaN,NaN,58000000,57000000,NaN,-1000000,NaN,-54000000,-33000000,NaN,NaN,NaN,NaN,57000000,57000000,NaN,NaN,NaN,NaN,-33000000,NaN,22000000,NaN,NaN,172000000,QUARTERLY,12
50,2013-07-31,USD,137000000,NaN,NaN,NaN,NaN,46000000,65000000,NaN,-20000000,NaN,-438000000,-55000000,NaN,NaN,NaN,NaN,52000000,52000000,NaN,NaN,NaN,NaN,-38000000,NaN,20000000,NaN,NaN,142000000,QUARTERLY,12
51,2013-04-30,USD,188000000,NaN,NaN,NaN,NaN,42000000,47000000,NaN,-20000000,NaN,-84000000,-36000000,NaN,NaN,NaN,NaN,47000000,47000000,NaN,NaN,NaN,NaN,-11000000,NaN,18000000,NaN,NaN,113000000,QUARTERLY,12
52,2013-01-31,USD,185000000,NaN,NaN,NaN,NaN,41000000,67000000,NaN,-14000000,NaN,-76000000,-42000000,NaN,NaN,NaN,NaN,42000000,42000000,NaN,NaN,NaN,NaN,-13000000,NaN,17000000,NaN,NaN,125000000,QUARTERLY,12
53,2012-10-31,USD,215000000,NaN,NaN,NaN,NaN,40000000,73000000,NaN,22000000,NaN,-74000000,-30000000,NaN,NaN,NaN,NaN,39000000,39000000,NaN,NaN,NaN,NaN,-10000000,NaN,14000000,NaN,NaN,159000000,QUARTERLY,12
54,2012-07-31,USD,128000000,NaN,NaN,NaN,NaN,40000000,65000000,NaN,2000000,NaN,-67000000,-42000000,NaN,NaN,NaN,NaN,37000000,37000000,NaN,NaN,NaN,NaN,-15000000,NaN,15000000,NaN,NaN,145000000,QUARTERLY,12
55,2012-04-30,USD,211000000,NaN,NaN,NaN,NaN,38000000,56000000,NaN,-25000000,NaN,-56000000,-20000000,NaN,NaN,NaN,NaN,32000000,32000000,NaN,NaN,NaN,NaN,-6000000,NaN,13000000,NaN,NaN,134000000,QUARTERLY,12
56,2012-01-31,USD,139000000,NaN,NaN,NaN,NaN,37000000,47000000,NaN,1000000,NaN,-47000000,-102000000,NaN,NaN,NaN,NaN,29000000,29000000,NaN,NaN,NaN,NaN,-79000000,NaN,11000000,NaN,NaN,125000000,QUARTERLY,12
57,2011-10-31,USD,195000000,NaN,NaN,NaN,NaN,39000000,37000000,NaN,6000000,NaN,-38000000,-32000000,NaN,NaN,NaN,NaN,27000000,27000000,NaN,NaN,NaN,NaN,-25000000,NaN,11000000,NaN,NaN,154000000,QUARTERLY,12
58,2011-07-31,USD,213000000,NaN,NaN,NaN,NaN,39000000,24000000,NaN,-6000000,NaN,-24000000,-81000000,NaN,NaN,NaN,NaN,22000000,22000000,NaN,NaN,NaN,NaN,-68000000,NaN,11000000,NaN,NaN,144000000,QUARTERLY,12
59,2011-04-30,USD,253000000,NaN,NaN,NaN,NaN,38000000,19000000,NaN,9000000,NaN,-19000000,-1000000,NaN,NaN,NaN,NaN,20000000,20000000,NaN,NaN,NaN,NaN,NaN,NaN,9000000,NaN,NaN,135000000,QUARTERLY,12
60,2011-01-31,USD,67000000,NaN,NaN,NaN,NaN,41000000,32000000,NaN,-14000000,NaN,-41000000,-224000000,NaN,NaN,NaN,NaN,17000000,17000000,NaN,NaN,NaN,NaN,NaN,NaN,7000000,NaN,NaN,119000000,QUARTERLY,12
61,2010-10-31,USD,217000000,NaN,NaN,NaN,NaN,40000000,30000000,NaN,-4000000,NaN,-30000000,7000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7000000,NaN,NaN,164000000,QUARTERLY,12
62,2010-07-31,USD,137000000,NaN,NaN,NaN,NaN,40000000,22000000,NaN,-6000000,NaN,-29000000,3000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7000000,NaN,NaN,123000000,QUARTERLY,12
63,2010-04-30,USD,115000000,NaN,NaN,NaN,NaN,40000000,18000000,NaN,-12000000,NaN,-18000000,15000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6000000,NaN,NaN,90000000,QUARTERLY,12
64,2010-01-31,USD,41000000,NaN,NaN,NaN,NaN,39000000,9000000,NaN,-4000000,NaN,-9000000,-360000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5000000,NaN,NaN,38000000,QUARTERLY,12
65,2009-10-31,USD,46000000,NaN,NaN,NaN,NaN,40000000,21000000,NaN,-9000000,NaN,-21000000,193000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5000000,NaN,NaN,-21000000,QUARTERLY,12
66,2009-07-31,USD,31000000,NaN,NaN,NaN,NaN,40000000,12000000,NaN,-2000000,NaN,-12000000,-6000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5000000,NaN,3000000,NaN,NaN,2000000,QUARTERLY,12
67,2009-04-30,USD,66000000,NaN,NaN,NaN,NaN,39000000,13000000,NaN,28000000,NaN,-18000000,-2000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4000000,NaN,NaN,-31000000,QUARTERLY,12
68,2009-01-31,USD,-4000000,NaN,NaN,NaN,NaN,41000000,12000000,NaN,10000000,NaN,-12000000,-2000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6000000,QUARTERLY,12
69,2008-10-31,USD,114000000,NaN,NaN,NaN,NaN,42000000,18000000,NaN,7000000,NaN,-45000000,-4000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1000000,NaN,3000000,NaN,NaN,18000000,QUARTERLY,12
70,2008-07-31,USD,60000000,NaN,NaN,NaN,NaN,40000000,19000000,NaN,-27000000,NaN,6000000,-1000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000000,NaN,NaN,44000000,QUARTERLY,12
71,2008-04-30,USD,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17000000,QUARTERLY,12
72,2008-01-31,USD,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4000000,QUARTERLY,12
73,2007-10-31,USD,146000000,NaN,NaN,NaN,NaN,NaN,37000000,NaN,28000000,NaN,5000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,QUARTERLY,12

In [71]:
df.drop(index=[71,72],axis=0,inplace=True)

In [72]:
schema_name = "alpha_vantage_db"
stock_id = get_stock_id(Stock, engine,ticker) #get from postgres
write_to_postgres(df,"cash_flow", stock_id, engine, schema_name,cash_flow_mapping)

In [ ]:
schema_name = "alpha_vantage_db"
stock_id = get_stock_id(Stock, engine,ticker) #get from postgres
for mapping in mapping_names:
    dict_to_pass = {mapping: function_names[mapping]}
    df = query_all_statements(ticker,dict_to_pass)
    time.sleep(15)
    df = df.replace('None', np.nan).where(pd.notnull(df), None)
    if mapping == "OVERVIEW":
        df.drop(columns=['Symbol'],inplace=True)
        df.loc[0,'Currency']='1'
        df['Currency'] = df['Currency'].astype('int64')
    elif mapping == "BALANCE_SHEET" or mapping == "CASH_FLOW" or mapping == "INCOME_STATEMENT" :
        if function_names[mapping] == "annualReports":
            df = df.assign(
                            report_type = "ANNUAL"
                            )
        elif function_names[mapping] == "quarterlyReports":
            df = df.assign(
                            report_type = "QUARTERLY"
                            )

    tablename = table_names[mapping]
    write_to_postgres(df,tablename, stock_id, engine, schema_name,mapping_names[mapping])

In [18]:
df.head()

,fiscalDateEnding,reportedCurrency,totalAssets,totalCurrentAssets,cashAndCashEquivalentsAtCarryingValue,cashAndShortTermInvestments,inventory,currentNetReceivables,totalNonCurrentAssets,propertyPlantEquipment,accumulatedDepreciationAmortizationPPE,intangibleAssets,intangibleAssetsExcludingGoodwill,goodwill,investments,longTermInvestments,shortTermInvestments,otherCurrentAssets,otherNonCurrentAssets,totalLiabilities,totalCurrentLiabilities,currentAccountsPayable,deferredRevenue,currentDebt,shortTermDebt,totalNonCurrentLiabilities,capitalLeaseObligations,longTermDebt,currentLongTermDebt,longTermDebtNoncurrent,shortLongTermDebtTotal,otherCurrentLiabilities,otherNonCurrentLiabilities,totalShareholderEquity,treasuryStock,retainedEarnings,commonStock,commonStockSharesOutstanding,report_type
0,2026-03-31,USD,371082000000,144114000000,36328000000,36328000000,6747000000,53511000000,226968000000,NaN,NaN,21334000000,21334000000,NaN,NaN,78088000000,32179000000,15349000000,NaN,264591000000,134641000000,57349000000,NaN,NaN,10307000000,129950000000,NaN,74404000000,10307000000,NaN,84711000000,57654000000,55546000000,106491000000,NaN,12359000000,99507000000,14768115000,QUARTERLY
1,2025-12-31,USD,379297000000,158104000000,45317000000,45317000000,5875000000,70320000000,221193000000,50159000000,NaN,NaN,NaN,NaN,NaN,77888000000,21590000000,15002000000,NaN,291107000000,162367000000,70587000000,NaN,NaN,13824000000,128740000000,NaN,76685000000,13824000000,NaN,90509000000,68543000000,52055000000,88190000000,NaN,-2177000000,95221000000,14810356000,QUARTERLY
2,2025-09-30,USD,359241000000,147957000000,35934000000,35934000000,5718000000,72957000000,211284000000,49834000000,NaN,NaN,NaN,NaN,NaN,77723000000,18763000000,14585000000,NaN,285508000000,165631000000,69860000000,NaN,NaN,22446000000,119877000000,NaN,78328000000,20329000000,NaN,112377000000,64270000000,41549000000,73733000000,NaN,-14264000000,93568000000,15004697000,QUARTERLY
3,2025-06-30,USD,331495000000,122491000000,36269000000,36269000000,5925000000,46835000000,209004000000,48508000000,NaN,NaN,NaN,NaN,NaN,77614000000,24907000000,14359000000,NaN,265665000000,141120000000,50374000000,NaN,NaN,19268000000,124545000000,NaN,82430000000,19268000000,NaN,101698000000,62499000000,42115000000,65830000000,NaN,-17607000000,89806000000,14948179000,QUARTERLY
4,2025-03-31,USD,331233000000,118674000000,28162000000,28162000000,6269000000,49798000000,212559000000,46876000000,NaN,NaN,NaN,NaN,NaN,84424000000,20336000000,14109000000,NaN,264437000000,144571000000,54126000000,NaN,NaN,19620000000,119866000000,NaN,78566000000,19620000000,NaN,98186000000,61849000000,41300000000,66796000000,NaN,-15552000000,88711000000,15056133000,QUARTERLY

### Adding ohlcv data

In [72]:
import yfinance as yf
ticker = "ACN"
df = yf.download(ticker, start="2000-01-01", interval="1d")
df.columns = df.columns.droplevel(1)
df = ( df.rename_axis(None, axis=1)
      .reset_index()
      )
df = df.assign(year=df['Date'].dt.year)

ohlcv_mapping = {
                    "Date":"date",
                    "Open":"open",
                    "Close":"close",
                    "Low":"low",
                    "High":"high",
                    "Volume":"volume"
                    }

tablename = "ohlcv"
stock_id = 14

write_to_postgres(df,tablename, stock_id, engine, schema_name,ohlcv_mapping)

[*********************100%***********************]  1 of 1 completed

still earning estimates missing