In [134]:
from sqlalchemy import create_engine, MetaData,Table,Column, Integer, String,text,select
from sqlalchemy.orm import Session
from sqlalchemy.orm import DeclarativeBase

from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column

from sqlalchemy import and_
from sqlalchemy import func,desc,asc
from sqlalchemy import cast, Numeric,Float

from datetime import date

import pandas as pd
pd.options.display.float_format = '{:.4f}'.format
import urllib.parse

In [2]:
with open("db_password.txt") as file:
    db_pw = file.read()

db_pw = db_pw.strip()
db_pw

'skisback@070126'

In [3]:
# Encode that '@' symbol!
encoded_pw = urllib.parse.quote_plus(db_pw)
url = f"postgresql://postgres:{encoded_pw}@localhost:5432/postgres"

### First step using sqlalchemy

In [4]:
engine = create_engine(url)

### Raw SQL query

In [ ]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT * FROM alpha_vantage_db.balance_sheet"))
    for row in result:
        x = row[0]
        print(x)

In [ ]:
# Use pd.read_sql instead of conn.execute
df = pd.read_sql("SELECT * FROM alpha_vantage_db.balance_sheet", engine)

# Just typing 'df' at the end of a cell makes it look beautiful
df.head()

,stock_id,fiscal_date_ending,reported_currency,total_assets,total_current_assets,cash_and_cash_equivalents_at_carrying_value,cash_and_short_term_investments,inventory,current_net_receivables,total_non_current_assets,...,current_long_term_debt,long_term_debt_noncurrent,short_long_term_debt_total,other_current_liabilities,other_non_current_liabilities,total_shareholder_equity,treasury_stock,retained_earnings,common_stock,common_stock_shares_outstanding
0,1,2025-09-30,USD,359241000000,147957000000,35934000000,35934000000,5718000000,72957000000,211284000000,...,20329000000,None,112377000000,64270000000,41549000000,73733000000,NaN,-14264000000,93568000000,15004697000
1,1,2024-09-30,USD,364980000000,152987000000,29943000000,29943000000,7286000000,66243000000,211993000000,...,20879000000,None,119059000000,50071000000,36634000000,56950000000,NaN,-19154000000,83276000000,15408095000
2,1,2023-09-30,USD,352583000000,143566000000,29965000000,29965000000,6331000000,29508000000,209017000000,...,15807000000,None,111947000000,58829000000,49848000000,62146000000,NaN,-214000000,73812000000,15812547000
3,1,2022-09-30,USD,352755000000,135405000000,23646000000,23646000000,4946000000,28184000000,217350000000,...,21110000000,None,120881000000,60845000000,49142000000,50672000000,NaN,-3068000000,64849000000,16325819000
4,1,2021-09-30,USD,351002000000,134836000000,34940000000,34940000000,6580000000,26278000000,216166000000,...,15613000000,None,124719000000,47493000000,28636000000,63090000000,NaN,5562000000,57365000000,16864919000

In [33]:
stmt = text("SELECT * FROM alpha_vantage_db.income_statement WHERE stock_id = 1")
with Session(engine) as session:
    result = session.execute(stmt)
    for row in result:
        print(f"Row: {row}")

Row: (1, datetime.date(2025, 9, 30), 'USD', Decimal('195201000000.0000'), Decimal('416161000000.0000'), Decimal('220960000000.0000'), Decimal('220960000000.0000'), Decimal('133050000000.0000'), Decimal('8077000000.0000'), Decimal('34550000000.0000'), Decimal('62151000000.0000'), None, None, None, None, None, None, None, Decimal('11698000000.0000'), Decimal('132729000000.0000'), Decimal('20719000000.0000'), None, Decimal('112010000000.0000'), None, Decimal('132729000000.0000'), Decimal('144427000000.0000'), Decimal('112010000000.0000'))
Row: (1, datetime.date(2024, 9, 30), 'USD', Decimal('180683000000.0000'), Decimal('391035000000.0000'), Decimal('210352000000.0000'), Decimal('210352000000.0000'), Decimal('123216000000.0000'), Decimal('26097000000.0000'), Decimal('31370000000.0000'), Decimal('57467000000.0000'), None, Decimal('0.0000'), Decimal('0.0000'), Decimal('0.0000'), None, None, None, Decimal('11445000000.0000'), Decimal('123485000000.0000'), Decimal('29749000000.0000'), None, Decimal('93736000000.0000'), None, Decimal('123216000000.0000'), Decimal('134661000000.0000'), Decimal('93736000000.0000'))
Row: (1, datetime.date(2023, 9, 30), 'USD', Decimal('169148000000.0000'), Decimal('383285000000.0000'), Decimal('214137000000.0000'), Decimal('214137000000.0000'), Decimal('114301000000.0000'), Decimal('24932000000.0000'), Decimal('29915000000.0000'), Decimal('54847000000.0000'), None, Decimal('-183000000.0000'), Decimal('3750000000.0000'), Decimal('3933000000.0000'), None, Decimal('-382000000.0000'), None, Decimal('11519000000.0000'), Decimal('113736000000.0000'), Decimal('16741000000.0000'), None, Decimal('96995000000.0000'), None, Decimal('114301000000.0000'), Decimal('125820000000.0000'), Decimal('96995000000.0000'))
Row: (1, datetime.date(2022, 9, 30), 'USD', Decimal('170782000000.0000'), Decimal('394328000000.0000'), Decimal('223546000000.0000'), Decimal('223546000000.0000'), Decimal('119437000000.0000'), Decimal('25094000000.0000'), Decimal('26251000000.0000'), Decimal('51573000000.0000'), None, Decimal('-106000000.0000'), Decimal('2825000000.0000'), Decimal('2931000000.0000'), None, Decimal('334000000.0000'), None, Decimal('11104000000.0000'), Decimal('119103000000.0000'), Decimal('19300000000.0000'), None, Decimal('99803000000.0000'), None, Decimal('119437000000.0000'), Decimal('130541000000.0000'), Decimal('99803000000.0000'))
Row: (1, datetime.date(2021, 9, 30), 'USD', Decimal('152836000000.0000'), Decimal('365817000000.0000'), Decimal('212981000000.0000'), Decimal('212981000000.0000'), Decimal('108949000000.0000'), Decimal('21973000000.0000'), Decimal('21914000000.0000'), Decimal('43887000000.0000'), None, Decimal('198000000.0000'), Decimal('2843000000.0000'), Decimal('2645000000.0000'), None, Decimal('258000000.0000'), None, Decimal('11284000000.0000'), Decimal('109207000000.0000'), Decimal('14527000000.0000'), None, Decimal('94680000000.0000'), None, Decimal('111852000000.0000'), Decimal('123136000000.0000'), Decimal('94680000000.0000'))
Row: (1, datetime.date(2020, 9, 30), 'USD', Decimal('104956000000.0000'), Decimal('274515000000.0000'), Decimal('169559000000.0000'), Decimal('169559000000.0000'), Decimal('66288000000.0000'), Decimal('19916000000.0000'), Decimal('18752000000.0000'), Decimal('38668000000.0000'), None, Decimal('890000000.0000'), Decimal('3763000000.0000'), Decimal('2873000000.0000'), None, Decimal('803000000.0000'), None, Decimal('11056000000.0000'), Decimal('67091000000.0000'), Decimal('9680000000.0000'), None, Decimal('57411000000.0000'), None, Decimal('69964000000.0000'), Decimal('81020000000.0000'), Decimal('57411000000.0000'))
Row: (1, datetime.date(2019, 9, 30), 'USD', Decimal('98392000000.0000'), Decimal('260174000000.0000'), Decimal('161782000000.0000'), Decimal('161782000000.0000'), Decimal('63930000000.0000'), Decimal('18245000000.0000'), Decimal('16217000000.0000'), Decimal('34462000000.0000'), None, Decimal('1385000000.0000'), Decimal('4961000000.0000'), Decimal('3576000000.0000'), None, Decimal('1807000000.0000'), None, Decimal('12547000000.0000'), Decimal('65737000000.0000'), Decimal('10481000000.0000'), None, Decimal('55256000000.0000'), None, Decimal('69313000000.0000'), Decimal('81860000000.0000'), Decimal('55256000000.0000'))
Row: (1, datetime.date(2018, 9, 30), 'USD', Decimal('101839000000.0000'), Decimal('265595000000.0000'), Decimal('163756000000.0000'), Decimal('163756000000.0000'), Decimal('70898000000.0000'), Decimal('16705000000.0000'), Decimal('14236000000.0000'), Decimal('30941000000.0000'), None, Decimal('2446000000.0000'), Decimal('5686000000.0000'), Decimal('3240000000.0000'), None, Decimal('2005000000.0000'), None, Decimal('10903000000.0000'), Decimal('72903000000.0000'), Decimal('13372000000.0000'), None, Decimal('59531000000.0000'), None, Decimal('76143000000.0000'), Decimal('87046000000.0000'), Decimal('59531000000.0000'))
Row: (1, datetime.date(2017, 9, 30), 'USD', Decimal('88186000000.0000'), Decimal('229234000000.0000'), Decimal('141048000000.0000'), Decimal('141048000000.0000'), Decimal('61344000000.0000'), Decimal('15261000000.0000'), Decimal('11581000000.0000'), Decimal('26842000000.0000'), None, Decimal('2878000000.0000'), Decimal('5201000000.0000'), Decimal('2323000000.0000'), None, Decimal('2745000000.0000'), None, Decimal('10157000000.0000'), Decimal('64089000000.0000'), Decimal('15738000000.0000'), None, Decimal('48351000000.0000'), None, Decimal('66412000000.0000'), Decimal('76569000000.0000'), Decimal('48351000000.0000'))
Row: (1, datetime.date(2016, 9, 30), 'USD', Decimal('84263000000.0000'), Decimal('215639000000.0000'), Decimal('131376000000.0000'), Decimal('131376000000.0000'), Decimal('60024000000.0000'), Decimal('14194000000.0000'), Decimal('10045000000.0000'), Decimal('24239000000.0000'), None, Decimal('2543000000.0000'), Decimal('3999000000.0000'), Decimal('1456000000.0000'), None, Decimal('1348000000.0000'), None, Decimal('10505000000.0000'), Decimal('61372000000.0000'), Decimal('15685000000.0000'), None, Decimal('45687000000.0000'), None, Decimal('62828000000.0000'), Decimal('73333000000.0000'), Decimal('45687000000.0000'))
Row: (1, datetime.date(2015, 9, 30), 'USD', Decimal('93626000000.0000'), Decimal('233715000000.0000'), Decimal('140089000000.0000'), Decimal('140089000000.0000'), Decimal('71230000000.0000'), Decimal('14329000000.0000'), Decimal('8067000000.0000'), Decimal('22396000000.0000'), None, None, None, Decimal('733000000.0000'), None, Decimal('1285000000.0000'), None, Decimal('11257000000.0000'), Decimal('72515000000.0000'), Decimal('19121000000.0000'), None, Decimal('53394000000.0000'), None, Decimal('73248000000.0000'), Decimal('84505000000.0000'), Decimal('53394000000.0000'))
Row: (1, datetime.date(2014, 9, 30), 'USD', Decimal('70537000000.0000'), Decimal('182795000000.0000'), Decimal('112258000000.0000'), Decimal('112258000000.0000'), Decimal('52503000000.0000'), Decimal('11993000000.0000'), Decimal('6041000000.0000'), Decimal('18034000000.0000'), None, None, None, Decimal('384000000.0000'), None, Decimal('980000000.0000'), None, Decimal('7946000000.0000'), Decimal('53483000000.0000'), Decimal('13973000000.0000'), None, Decimal('39510000000.0000'), None, Decimal('53867000000.0000'), Decimal('61813000000.0000'), Decimal('39510000000.0000'))
Row: (1, datetime.date(2013, 9, 30), 'USD', Decimal('64304000000.0000'), Decimal('170910000000.0000'), Decimal('106606000000.0000'), Decimal('106606000000.0000'), Decimal('48999000000.0000'), Decimal('9730000000.0000'), Decimal('4475000000.0000'), Decimal('15305000000.0000'), None, None, None, Decimal('136000000.0000'), None, Decimal('1156000000.0000'), None, Decimal('6757000000.0000'), Decimal('50155000000.0000'), Decimal('13118000000.0000'), None, Decimal('37037000000.0000'), None, Decimal('50291000000.0000'), Decimal('57048000000.0000'), Decimal('37037000000.0000'))
Row: (1, datetime.date(2012, 9, 30), 'USD', Decimal('68662000000.0000'), Decimal('156508000000.0000'), Decimal('87846000000.0000'), Decimal('87846000000.0000'), Decimal('55241000000.0000'), Decimal('9040000000.0000'), Decimal('3381000000.0000'), Decimal('13421000000.0000'), None, None, None, Decimal('522000000.0000'), None, Decimal('522000000.0000'), None, Decimal('3277000000.0000'), Decimal('55763000000.0000'), Decimal('14030000000.0000'), None, Decimal('41733000000.0000'), None, Decimal('55763000000.0000'), Decimal('59040000000.0000'), Decimal('41733000000.0000'))
Row: (1, datetime.date(2011, 9, 30), 'USD', Decimal('43818000000.0000'), Decimal('108249000000.0000'), Decimal('64431000000.0000'), Decimal('64431000000.0000'), Decimal('33790000000.0000'), Decimal('7599000000.0000'), Decimal('2429000000.0000'), Decimal('10028000000.0000'), None, None, None, Decimal('415000000.0000'), None, Decimal('415000000.0000'), None, Decimal('1814000000.0000'), Decimal('34205000000.0000'), Decimal('8283000000.0000'), None, Decimal('25922000000.0000'), None, Decimal('34205000000.0000'), Decimal('36019000000.0000'), Decimal('25922000000.0000'))
Row: (1, datetime.date(2010, 9, 30), 'USD', Decimal('25684000000.0000'), Decimal('65225000000.0000'), Decimal('39541000000.0000'), Decimal('39541000000.0000'), Decimal('18385000000.0000'), Decimal('5517000000.0000'), Decimal('1782000000.0000'), Decimal('7299000000.0000'), None, None, None, Decimal('155000000.0000'), None, Decimal('155000000.0000'), None, Decimal('1027000000.0000'), Decimal('18540000000.0000'), Decimal('4527000000.0000'), None, Decimal('14013000000.0000'), None, Decimal('18385000000.0000'), Decimal('19412000000.0000'), Decimal('14013000000.0000'))
Row: (1, datetime.date(2009, 9, 30), 'USD', Decimal('17222000000.0000'), Decimal('42905000000.0000'), Decimal('25683000000.0000'), Decimal('25683000000.0000'), Decimal('11740000000.0000'), Decimal('4149000000.0000'), Decimal('1333000000.0000'), Decimal('5482000000.0000'), None, None, None, Decimal('326000000.0000'), None, Decimal('326000000.0000'), None, Decimal('734000000.0000'), Decimal('12066000000.0000'), Decimal('3831000000.0000'), None, Decimal('8235000000.0000'), None, Decimal('11740000000.0000'), Decimal('12474000000.0000'), Decimal('8235000000.0000'))
Row: (1, datetime.date(2008, 9, 30), 'USD', Decimal('11145000000.0000'), Decimal('32479000000.0000'), Decimal('21334000000.0000'), Decimal('21334000000.0000'), Decimal('6275000000.0000'), Decimal('3761000000.0000'), Decimal('1109000000.0000'), Decimal('4870000000.0000'), None, None, None, Decimal('620000000.0000'), None, None, None, Decimal('409000000.0000'), Decimal('6895000000.0000'), Decimal('2061000000.0000'), None, None, None, Decimal('6895000000.0000'), Decimal('7304000000.0000'), Decimal('4834000000.0000'))
Row: (1, datetime.date(2007, 9, 30), 'USD', Decimal('8154000000.0000'), Decimal('24006000000.0000'), Decimal('15852000000.0000'), Decimal('15852000000.0000'), Decimal('4409000000.0000'), Decimal('2963000000.0000'), Decimal('782000000.0000'), Decimal('3745000000.0000'), None, None, None, Decimal('599000000.0000'), None, None, None, Decimal('317000000.0000'), Decimal('5008000000.0000'), Decimal('1512000000.0000'), None, None, None, Decimal('4407000000.0000'), Decimal('4724000000.0000'), Decimal('3495000000.0000'))
Row: (1, datetime.date(2006, 9, 30), 'USD', Decimal('5598000000.0000'), Decimal('19315000000.0000'), Decimal('13717000000.0000'), Decimal('13717000000.0000'), Decimal('2453000000.0000'), Decimal('2433000000.0000'), Decimal('712000000.0000'), Decimal('3145000000.0000'), None, None, None, Decimal('365000000.0000'), None, None, None, Decimal('225000000.0000'), Decimal('2818000000.0000'), Decimal('829000000.0000'), None, None, None, Decimal('2453000000.0000'), Decimal('2678000000.0000'), Decimal('1989000000.0000'))

### Selecting tables from postgres

### Core way

In [ ]:
metadata_obj = MetaData()

In [ ]:
stock_table = Table(
    "stock",
    metadata_obj,
    autoload_with=engine,
    schema="alpha_vantage_db"  # <--- THIS IS THE KEY
)

In [ ]:
#stmt = select(stock_table).where(stock_table.c.stock_id == 1)
stmt = select(stock_table)
print(stmt)

SELECT alpha_vantage_db.stock.stock_id, alpha_vantage_db.stock.ticker
FROM alpha_vantage_db.stock

In [67]:
with engine.connect() as conn:
    for row in conn.execute(stmt):
        print(row)

(1, 'APPL')
(2, 'TSLA')
(3, 'MSFT')

## ORM way

In [19]:
# declarative base class
class Base(DeclarativeBase):
    pass

# Load the "Parent" first
class BalanceSheet(Base):
    __tablename__ = "balance_sheet"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

# Then load the "Children"
class IncomeStatement(Base):
    __tablename__ = "income_statement"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class CashFlow(Base):
    __tablename__ = "cash_flow"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

#### Overwriting table defintion in sqlalchemy

In [6]:
class Base(DeclarativeBase):
    pass

class CashFlowStatement(Base):
    __tablename__ = "income_statement"
    __table_args__ = {"autoload_with": engine, 
                      "schema": "alpha_vantage_db",
                      "extend_existing": True}
    
    id: Mapped[int] = mapped_column("stock_id",primary_key=True)
    curr: Mapped[str] = mapped_column("reported_currency")

### Reading tables using sqlalchemy

In [72]:
stmt = select(BalanceSheet).where(BalanceSheet.stock_id == 2)
with Session(engine) as session:
    results =session.execute(stmt).scalars().all()
    for entry in results:
        print(f"Stock ID: {entry.stock_id} | Total Assets: {entry.total_assets}")

Stock ID: 2 | Total Assets: 619003000000.0000
Stock ID: 2 | Total Assets: 512163000000.0000
Stock ID: 2 | Total Assets: 411976000000.0000
Stock ID: 2 | Total Assets: 364840000000.0000
Stock ID: 2 | Total Assets: 333779000000.0000
Stock ID: 2 | Total Assets: 301311000000.0000
Stock ID: 2 | Total Assets: 286556000000.0000
Stock ID: 2 | Total Assets: 258848000000.0000
Stock ID: 2 | Total Assets: 241086000000.0000
Stock ID: 2 | Total Assets: 193694000000.0000
Stock ID: 2 | Total Assets: 174472000000.0000
Stock ID: 2 | Total Assets: 172384000000.0000
Stock ID: 2 | Total Assets: 142431000000.0000
Stock ID: 2 | Total Assets: 121271000000.0000
Stock ID: 2 | Total Assets: 108704000000.0000
Stock ID: 2 | Total Assets: 86113000000.0000
Stock ID: 2 | Total Assets: 77888000000.0000
Stock ID: 2 | Total Assets: 72793000000.0000
Stock ID: 2 | Total Assets: 63171000000.0000
Stock ID: 2 | Total Assets: 69597000000.0000

### Executing queries using pandas

In [7]:
stmt = select(BalanceSheet).where(BalanceSheet.stock_id == 1)
df = pd.read_sql(stmt, engine)
df # This will show the nice formatted table

,stock_id,fiscal_date_ending,reported_currency,total_assets,total_current_assets,cash_and_cash_equivalents_at_carrying_value,cash_and_short_term_investments,inventory,current_net_receivables,total_non_current_assets,...,current_long_term_debt,long_term_debt_noncurrent,short_long_term_debt_total,other_current_liabilities,other_non_current_liabilities,total_shareholder_equity,treasury_stock,retained_earnings,common_stock,common_stock_shares_outstanding
0,1,2025-09-30,USD,359241000000,147957000000,35934000000,35934000000,5718000000,72957000000,211284000000,...,20329000000,None,112377000000,64270000000,41549000000,73733000000,NaN,-14264000000,93568000000,15004697000
1,1,2024-09-30,USD,364980000000,152987000000,29943000000,29943000000,7286000000,66243000000,211993000000,...,20879000000,None,119059000000,50071000000,36634000000,56950000000,NaN,-19154000000,83276000000,15408095000
2,1,2023-09-30,USD,352583000000,143566000000,29965000000,29965000000,6331000000,29508000000,209017000000,...,15807000000,None,111947000000,58829000000,49848000000,62146000000,NaN,-214000000,73812000000,15812547000
3,1,2022-09-30,USD,352755000000,135405000000,23646000000,23646000000,4946000000,28184000000,217350000000,...,21110000000,None,120881000000,60845000000,49142000000,50672000000,NaN,-3068000000,64849000000,16325819000
4,1,2021-09-30,USD,351002000000,134836000000,34940000000,34940000000,6580000000,26278000000,216166000000,...,15613000000,None,124719000000,47493000000,28636000000,63090000000,NaN,5562000000,57365000000,16864919000
5,1,2020-09-30,USD,323888000000,143713000000,38016000000,38016000000,4061000000,16120000000,180175000000,...,13769000000,None,112436000000,42684000000,26320000000,65339000000,NaN,14966000000,50779000000,17528214000
6,1,2019-09-30,USD,338516000000,162819000000,48844000000,48844000000,4106000000,22926000000,175697000000,...,16240000000,None,108047000000,37720000000,20958000000,90488000000,NaN,45898000000,45174000000,18595652000
7,1,2018-09-30,USD,365725000000,131339000000,25913000000,25913000000,3956000000,23186000000,234386000000,...,20748000000,None,114483000000,32687000000,11165000000,107147000000,NaN,70400000000,40201000000,20000436000
8,1,2017-09-30,USD,375319000000,128645000000,20289000000,20289000000,4855000000,35673000000,246674000000,...,18473000000,None,115680000000,25744000000,40415000000,134047000000,0,98330000000,35867000000,21006768000
9,1,2016-09-30,USD,321686000000,106869000000,20484000000,20484000000,2132000000,29299000000,214817000000,...,11605000000,None,87032000000,22027000000,36074000000,128249000000,NaN,96364000000,31251000000,22001124000
10,1,2015-09-30,USD,290479000000,89378000000,21120000000,21120000000,2349000000,30343000000,201101000000,...,2513000000,None,64462000000,25181000000,33427000000,119355000000,0,92284000000,27416000000,23172276000
11,1,2014-09-30,USD,231839000000,68531000000,13844000000,13844000000,2111000000,4232000000,163308000000,...,35295000000,None,35295000000,18453000000,24826000000,111547000000,0,87152000000,23313000000,24490652000
12,1,2013-09-30,USD,207000000000,73286000000,14259000000,14259000000,1764000000,2172000000,133714000000,...,NaN,None,16960000000,13856000000,20208000000,123549000000,0,104256000000,19764000000,26086536000
13,1,2012-09-30,USD,176064000000,57653000000,10746000000,10746000000,791000000,5551000000,118411000000,...,NaN,None,NaN,11414000000,16664000000,118210000000,0,101289000000,16422000000,26469940000
14,1,2011-09-30,USD,116371000000,44988000000,9815000000,9815000000,776000000,5369000000,71383000000,...,NaN,None,NaN,9247000000,10100000000,76615000000,0,62841000000,13331000000,26226060000
15,1,2010-09-30,USD,75183000000,41678000000,11261000000,11261000000,1051000000,5510000000,33505000000,...,NaN,None,NaN,5723000000,5531000000,47791000000,0,37169000000,10668000000,25891936000
16,1,2009-09-30,USD,53851000000,36265000000,5263000000,5263000000,455000000,3361000000,17586000000,...,NaN,None,NaN,3376000000,3502000000,27832000000,0,19538000000,8210000000,25396140000
17,1,2008-09-30,USD,39572000000,34690000000,11875000000,11875000000,509000000,2422000000,4882000000,...,NaN,None,NaN,3719000000,NaN,21030000000,NaN,13845000000,7177000000,25259892000
18,1,2007-09-30,USD,25347000000,21956000000,9352000000,9352000000,346000000,4029000000,3391000000,...,NaN,None,NaN,2919000000,NaN,14532000000,NaN,9101000000,5368000000,24900176000
19,1,2006-09-30,USD,17205000000,14509000000,6392000000,6392000000,270000000,2845000000,2696000000,...,NaN,None,NaN,2335000000,NaN,9984000000,NaN,5607000000,4355000000,24570728000

In [10]:
stmt = select(CashFlowStatement).where(CashFlowStatement.id == 1)
df = pd.read_sql(stmt, engine)
df # This will show the nice formatted table

,stock_id,fiscal_date_ending,reported_currency,gross_profit,total_revenue,cost_of_revenue,cost_of_goods_and_services_sold,operating_income,selling_general_and_administrative,research_and_development,...,depreciation,depreciation_and_amortization,income_before_tax,income_tax_expense,interest_and_debt_expense,net_income_from_continuing_operations,comprehensive_income_net_of_tax,ebit,ebitda,net_income
0,1,2025-09-30,USD,195201000000,416161000000,220960000000,220960000000,133050000000,8077000000,34550000000,...,None,11698000000,132729000000,20719000000,None,112010000000,None,132729000000,144427000000,112010000000
1,1,2024-09-30,USD,180683000000,391035000000,210352000000,210352000000,123216000000,26097000000,31370000000,...,None,11445000000,123485000000,29749000000,None,93736000000,None,123216000000,134661000000,93736000000
2,1,2023-09-30,USD,169148000000,383285000000,214137000000,214137000000,114301000000,24932000000,29915000000,...,None,11519000000,113736000000,16741000000,None,96995000000,None,114301000000,125820000000,96995000000
3,1,2022-09-30,USD,170782000000,394328000000,223546000000,223546000000,119437000000,25094000000,26251000000,...,None,11104000000,119103000000,19300000000,None,99803000000,None,119437000000,130541000000,99803000000
4,1,2021-09-30,USD,152836000000,365817000000,212981000000,212981000000,108949000000,21973000000,21914000000,...,None,11284000000,109207000000,14527000000,None,94680000000,None,111852000000,123136000000,94680000000
5,1,2020-09-30,USD,104956000000,274515000000,169559000000,169559000000,66288000000,19916000000,18752000000,...,None,11056000000,67091000000,9680000000,None,57411000000,None,69964000000,81020000000,57411000000
6,1,2019-09-30,USD,98392000000,260174000000,161782000000,161782000000,63930000000,18245000000,16217000000,...,None,12547000000,65737000000,10481000000,None,55256000000,None,69313000000,81860000000,55256000000
7,1,2018-09-30,USD,101839000000,265595000000,163756000000,163756000000,70898000000,16705000000,14236000000,...,None,10903000000,72903000000,13372000000,None,59531000000,None,76143000000,87046000000,59531000000
8,1,2017-09-30,USD,88186000000,229234000000,141048000000,141048000000,61344000000,15261000000,11581000000,...,None,10157000000,64089000000,15738000000,None,48351000000,None,66412000000,76569000000,48351000000
9,1,2016-09-30,USD,84263000000,215639000000,131376000000,131376000000,60024000000,14194000000,10045000000,...,None,10505000000,61372000000,15685000000,None,45687000000,None,62828000000,73333000000,45687000000
10,1,2015-09-30,USD,93626000000,233715000000,140089000000,140089000000,71230000000,14329000000,8067000000,...,None,11257000000,72515000000,19121000000,None,53394000000,None,73248000000,84505000000,53394000000
11,1,2014-09-30,USD,70537000000,182795000000,112258000000,112258000000,52503000000,11993000000,6041000000,...,None,7946000000,53483000000,13973000000,None,39510000000,None,53867000000,61813000000,39510000000
12,1,2013-09-30,USD,64304000000,170910000000,106606000000,106606000000,48999000000,9730000000,4475000000,...,None,6757000000,50155000000,13118000000,None,37037000000,None,50291000000,57048000000,37037000000
13,1,2012-09-30,USD,68662000000,156508000000,87846000000,87846000000,55241000000,9040000000,3381000000,...,None,3277000000,55763000000,14030000000,None,41733000000,None,55763000000,59040000000,41733000000
14,1,2011-09-30,USD,43818000000,108249000000,64431000000,64431000000,33790000000,7599000000,2429000000,...,None,1814000000,34205000000,8283000000,None,25922000000,None,34205000000,36019000000,25922000000
15,1,2010-09-30,USD,25684000000,65225000000,39541000000,39541000000,18385000000,5517000000,1782000000,...,None,1027000000,18540000000,4527000000,None,14013000000,None,18385000000,19412000000,14013000000
16,1,2009-09-30,USD,17222000000,42905000000,25683000000,25683000000,11740000000,4149000000,1333000000,...,None,734000000,12066000000,3831000000,None,8235000000,None,11740000000,12474000000,8235000000
17,1,2008-09-30,USD,11145000000,32479000000,21334000000,21334000000,6275000000,3761000000,1109000000,...,None,409000000,6895000000,2061000000,None,NaN,None,6895000000,7304000000,4834000000
18,1,2007-09-30,USD,8154000000,24006000000,15852000000,15852000000,4409000000,2963000000,782000000,...,None,317000000,5008000000,1512000000,None,NaN,None,4407000000,4724000000,3495000000
19,1,2006-09-30,USD,5598000000,19315000000,13717000000,13717000000,2453000000,2433000000,712000000,...,None,225000000,2818000000,829000000,None,NaN,None,2453000000,2678000000,1989000000

In [106]:
stmt = select(CashFlowStatement.id,CashFlowStatement.curr).where(CashFlowStatement.id == 1)
df = pd.read_sql(stmt, engine)
df # This will show the nice formatted table

    stock_id reported_currency
0          1               USD
1          1               USD
2          1               USD
3          1               USD
4          1               USD
5          1               USD
6          1               USD
7          1               USD
8          1               USD
9          1               USD
10         1               USD
11         1               USD
12         1               USD
13         1               USD
14         1               USD
15         1               USD
16         1               USD
17         1               USD
18         1               USD
19         1               USD

In [11]:
stmt = select(IncomeStatement).where(IncomeStatement.stock_id == 1)
df = pd.read_sql(stmt, engine)
df # This will show the nice formatted table

,stock_id,fiscal_date_ending,reported_currency,gross_profit,total_revenue,cost_of_revenue,cost_of_goods_and_services_sold,operating_income,selling_general_and_administrative,research_and_development,...,depreciation,depreciation_and_amortization,income_before_tax,income_tax_expense,interest_and_debt_expense,net_income_from_continuing_operations,comprehensive_income_net_of_tax,ebit,ebitda,net_income
0,1,2025-09-30,USD,195201000000,416161000000,220960000000,220960000000,133050000000,8077000000,34550000000,...,None,11698000000,132729000000,20719000000,None,112010000000,None,132729000000,144427000000,112010000000
1,1,2024-09-30,USD,180683000000,391035000000,210352000000,210352000000,123216000000,26097000000,31370000000,...,None,11445000000,123485000000,29749000000,None,93736000000,None,123216000000,134661000000,93736000000
2,1,2023-09-30,USD,169148000000,383285000000,214137000000,214137000000,114301000000,24932000000,29915000000,...,None,11519000000,113736000000,16741000000,None,96995000000,None,114301000000,125820000000,96995000000
3,1,2022-09-30,USD,170782000000,394328000000,223546000000,223546000000,119437000000,25094000000,26251000000,...,None,11104000000,119103000000,19300000000,None,99803000000,None,119437000000,130541000000,99803000000
4,1,2021-09-30,USD,152836000000,365817000000,212981000000,212981000000,108949000000,21973000000,21914000000,...,None,11284000000,109207000000,14527000000,None,94680000000,None,111852000000,123136000000,94680000000
5,1,2020-09-30,USD,104956000000,274515000000,169559000000,169559000000,66288000000,19916000000,18752000000,...,None,11056000000,67091000000,9680000000,None,57411000000,None,69964000000,81020000000,57411000000
6,1,2019-09-30,USD,98392000000,260174000000,161782000000,161782000000,63930000000,18245000000,16217000000,...,None,12547000000,65737000000,10481000000,None,55256000000,None,69313000000,81860000000,55256000000
7,1,2018-09-30,USD,101839000000,265595000000,163756000000,163756000000,70898000000,16705000000,14236000000,...,None,10903000000,72903000000,13372000000,None,59531000000,None,76143000000,87046000000,59531000000
8,1,2017-09-30,USD,88186000000,229234000000,141048000000,141048000000,61344000000,15261000000,11581000000,...,None,10157000000,64089000000,15738000000,None,48351000000,None,66412000000,76569000000,48351000000
9,1,2016-09-30,USD,84263000000,215639000000,131376000000,131376000000,60024000000,14194000000,10045000000,...,None,10505000000,61372000000,15685000000,None,45687000000,None,62828000000,73333000000,45687000000
10,1,2015-09-30,USD,93626000000,233715000000,140089000000,140089000000,71230000000,14329000000,8067000000,...,None,11257000000,72515000000,19121000000,None,53394000000,None,73248000000,84505000000,53394000000
11,1,2014-09-30,USD,70537000000,182795000000,112258000000,112258000000,52503000000,11993000000,6041000000,...,None,7946000000,53483000000,13973000000,None,39510000000,None,53867000000,61813000000,39510000000
12,1,2013-09-30,USD,64304000000,170910000000,106606000000,106606000000,48999000000,9730000000,4475000000,...,None,6757000000,50155000000,13118000000,None,37037000000,None,50291000000,57048000000,37037000000
13,1,2012-09-30,USD,68662000000,156508000000,87846000000,87846000000,55241000000,9040000000,3381000000,...,None,3277000000,55763000000,14030000000,None,41733000000,None,55763000000,59040000000,41733000000
14,1,2011-09-30,USD,43818000000,108249000000,64431000000,64431000000,33790000000,7599000000,2429000000,...,None,1814000000,34205000000,8283000000,None,25922000000,None,34205000000,36019000000,25922000000
15,1,2010-09-30,USD,25684000000,65225000000,39541000000,39541000000,18385000000,5517000000,1782000000,...,None,1027000000,18540000000,4527000000,None,14013000000,None,18385000000,19412000000,14013000000
16,1,2009-09-30,USD,17222000000,42905000000,25683000000,25683000000,11740000000,4149000000,1333000000,...,None,734000000,12066000000,3831000000,None,8235000000,None,11740000000,12474000000,8235000000
17,1,2008-09-30,USD,11145000000,32479000000,21334000000,21334000000,6275000000,3761000000,1109000000,...,None,409000000,6895000000,2061000000,None,NaN,None,6895000000,7304000000,4834000000
18,1,2007-09-30,USD,8154000000,24006000000,15852000000,15852000000,4409000000,2963000000,782000000,...,None,317000000,5008000000,1512000000,None,NaN,None,4407000000,4724000000,3495000000
19,1,2006-09-30,USD,5598000000,19315000000,13717000000,13717000000,2453000000,2433000000,712000000,...,None,225000000,2818000000,829000000,None,NaN,None,2453000000,2678000000,1989000000

### JOIN Statement

In [ ]:
stmt = (
    select(BalanceSheet.stock_id,BalanceSheet.fiscal_date_ending,BalanceSheet.total_assets, IncomeStatement.net_income)
    .join(
        IncomeStatement, 
        and_(
            BalanceSheet.stock_id == IncomeStatement.stock_id,
            BalanceSheet.fiscal_date_ending == IncomeStatement.fiscal_date_ending
        )
    )
)

SELECT alpha_vantage_db.balance_sheet.stock_id, alpha_vantage_db.balance_sheet.fiscal_date_ending, alpha_vantage_db.balance_sheet.total_assets, alpha_vantage_db.income_statement.net_income
FROM alpha_vantage_db.balance_sheet JOIN alpha_vantage_db.income_statement ON alpha_vantage_db.balance_sheet.stock_id = alpha_vantage_db.income_statement.stock_id AND alpha_vantage_db.balance_sheet.fiscal_date_ending = alpha_vantage_db.income_statement.fiscal_date_ending

In [ ]:
df = pd.read_sql(stmt, engine)
df

    stock_id fiscal_date_ending  total_assets   net_income
0          1         2025-09-30  359241000000 112010000000
1          1         2024-09-30  364980000000  93736000000
2          1         2023-09-30  352583000000  96995000000
3          1         2022-09-30  352755000000  99803000000
4          1         2021-09-30  351002000000  94680000000
5          1         2020-09-30  323888000000  57411000000
6          1         2019-09-30  338516000000  55256000000
7          1         2018-09-30  365725000000  59531000000
8          1         2017-09-30  375319000000  48351000000
9          1         2016-09-30  321686000000  45687000000
10         1         2015-09-30  290479000000  53394000000
11         1         2014-09-30  231839000000  39510000000
12         1         2013-09-30  207000000000  37037000000
13         1         2012-09-30  176064000000  41733000000
14         1         2011-09-30  116371000000  25922000000
15         1         2010-09-30   75183000000  14013000000
16         1         2009-09-30   53851000000   8235000000
17         1         2008-09-30   39572000000   4834000000
18         1         2007-09-30   25347000000   3495000000
19         1         2006-09-30   17205000000   1989000000
20         2         2025-06-30  619003000000 101832000000
21         2         2024-06-30  512163000000  88136000000
22         2         2023-06-30  411976000000  72361000000
23         2         2022-06-30  364840000000  72738000000
24         2         2021-06-30  333779000000  61271000000
25         2         2020-06-30  301311000000  44281000000
26         2         2019-06-30  286556000000  39240000000
27         2         2018-06-30  258848000000  16571000000
28         2         2017-06-30  241086000000  25489000000
29         2         2016-06-30  193694000000  20539000000
30         2         2015-06-30  174472000000  12193000000
31         2         2014-06-30  172384000000  22074000000
32         2         2013-06-30  142431000000  21863000000
33         2         2012-06-30  121271000000  16978000000
34         2         2011-06-30  108704000000  23150000000
35         2         2010-06-30   86113000000  18760000000
36         2         2009-06-30   77888000000  14569000000
37         2         2008-06-30   72793000000  17681000000
38         2         2007-06-30   63171000000  14065000000
39         2         2006-06-30   69597000000  12599000000
40         3         2025-12-31  137806000000   3794000000
41         3         2024-12-31  122070000000   7130000000
42         3         2023-12-31  106618000000  14974000000
43         3         2022-12-31   82338000000  12587000000
44         3         2021-12-31   62131000000   5644000000
45         3         2020-12-31   52148000000    721000000
46         3         2019-12-31   34309000000   -862000000
47         3         2018-12-31   29740000000   -976000000
48         3         2017-12-31   28655372000  -1962000000
49         3         2016-12-31   22664076000   -674914000
50         3         2015-12-31    8067939000   -888663000
51         3         2014-12-31    5830667000   -294040000
52         3         2013-12-31    2416930000    -74014000
53         3         2012-12-31    1114190000   -396213000
54         3         2011-12-31     713448000   -254411000
55         3         2010-12-31     386082000   -154328000
56         3         2009-12-31     130424000    -55740000
57         3         2008-12-31      51699000    -82782000
58         3         2007-12-31      34837000    -78157000
59         3         2006-12-31           NaN    -29957000

### Order By

In [26]:
stmt = select(BalanceSheet).order_by(BalanceSheet.stock_id,BalanceSheet.total_assets.desc())
pd.read_sql(stmt,engine)

,stock_id,fiscal_date_ending,reported_currency,total_assets,total_current_assets,cash_and_cash_equivalents_at_carrying_value,cash_and_short_term_investments,inventory,current_net_receivables,total_non_current_assets,...,current_long_term_debt,long_term_debt_noncurrent,short_long_term_debt_total,other_current_liabilities,other_non_current_liabilities,total_shareholder_equity,treasury_stock,retained_earnings,common_stock,common_stock_shares_outstanding
0,1,2017-09-30,USD,375319000000,128645000000,20289000000,20289000000,4855000000,35673000000,246674000000,...,18473000000,None,115680000000,25744000000,40415000000,134047000000,0,98330000000,35867000000,21006768000
1,1,2018-09-30,USD,365725000000,131339000000,25913000000,25913000000,3956000000,23186000000,234386000000,...,20748000000,None,114483000000,32687000000,11165000000,107147000000,NaN,70400000000,40201000000,20000436000
2,1,2024-09-30,USD,364980000000,152987000000,29943000000,29943000000,7286000000,66243000000,211993000000,...,20879000000,None,119059000000,50071000000,36634000000,56950000000,NaN,-19154000000,83276000000,15408095000
3,1,2025-09-30,USD,359241000000,147957000000,35934000000,35934000000,5718000000,72957000000,211284000000,...,20329000000,None,112377000000,64270000000,41549000000,73733000000,NaN,-14264000000,93568000000,15004697000
4,1,2022-09-30,USD,352755000000,135405000000,23646000000,23646000000,4946000000,28184000000,217350000000,...,21110000000,None,120881000000,60845000000,49142000000,50672000000,NaN,-3068000000,64849000000,16325819000
5,1,2023-09-30,USD,352583000000,143566000000,29965000000,29965000000,6331000000,29508000000,209017000000,...,15807000000,None,111947000000,58829000000,49848000000,62146000000,NaN,-214000000,73812000000,15812547000
6,1,2021-09-30,USD,351002000000,134836000000,34940000000,34940000000,6580000000,26278000000,216166000000,...,15613000000,None,124719000000,47493000000,28636000000,63090000000,NaN,5562000000,57365000000,16864919000
7,1,2019-09-30,USD,338516000000,162819000000,48844000000,48844000000,4106000000,22926000000,175697000000,...,16240000000,None,108047000000,37720000000,20958000000,90488000000,NaN,45898000000,45174000000,18595652000
8,1,2020-09-30,USD,323888000000,143713000000,38016000000,38016000000,4061000000,16120000000,180175000000,...,13769000000,None,112436000000,42684000000,26320000000,65339000000,NaN,14966000000,50779000000,17528214000
9,1,2016-09-30,USD,321686000000,106869000000,20484000000,20484000000,2132000000,29299000000,214817000000,...,11605000000,None,87032000000,22027000000,36074000000,128249000000,NaN,96364000000,31251000000,22001124000
10,1,2015-09-30,USD,290479000000,89378000000,21120000000,21120000000,2349000000,30343000000,201101000000,...,2513000000,None,64462000000,25181000000,33427000000,119355000000,0,92284000000,27416000000,23172276000
11,1,2014-09-30,USD,231839000000,68531000000,13844000000,13844000000,2111000000,4232000000,163308000000,...,35295000000,None,35295000000,18453000000,24826000000,111547000000,0,87152000000,23313000000,24490652000
12,1,2013-09-30,USD,207000000000,73286000000,14259000000,14259000000,1764000000,2172000000,133714000000,...,NaN,None,16960000000,13856000000,20208000000,123549000000,0,104256000000,19764000000,26086536000
13,1,2012-09-30,USD,176064000000,57653000000,10746000000,10746000000,791000000,5551000000,118411000000,...,NaN,None,NaN,11414000000,16664000000,118210000000,0,101289000000,16422000000,26469940000
14,1,2011-09-30,USD,116371000000,44988000000,9815000000,9815000000,776000000,5369000000,71383000000,...,NaN,None,NaN,9247000000,10100000000,76615000000,0,62841000000,13331000000,26226060000
15,1,2010-09-30,USD,75183000000,41678000000,11261000000,11261000000,1051000000,5510000000,33505000000,...,NaN,None,NaN,5723000000,5531000000,47791000000,0,37169000000,10668000000,25891936000
16,1,2009-09-30,USD,53851000000,36265000000,5263000000,5263000000,455000000,3361000000,17586000000,...,NaN,None,NaN,3376000000,3502000000,27832000000,0,19538000000,8210000000,25396140000
17,1,2008-09-30,USD,39572000000,34690000000,11875000000,11875000000,509000000,2422000000,4882000000,...,NaN,None,NaN,3719000000,NaN,21030000000,NaN,13845000000,7177000000,25259892000
18,1,2007-09-30,USD,25347000000,21956000000,9352000000,9352000000,346000000,4029000000,3391000000,...,NaN,None,NaN,2919000000,NaN,14532000000,NaN,9101000000,5368000000,24900176000
19,1,2006-09-30,USD,17205000000,14509000000,6392000000,6392000000,270000000,2845000000,2696000000,...,NaN,None,NaN,2335000000,NaN,9984000000,NaN,5607000000,4355000000,24570728000
20,2,2025-06-30,USD,619003000000,191131000000,30242000000,30242000000,938000000,69905000000,427872000000,...,2999000000,None,112184000000,37344000000,45186000000,343479000000,NaN,237731000000,109095000000,7465000000
21,2,2024-06-30,USD,512163000000,159734000000,18315000000,18315000000,1246000000,56924000000,352429000000,...,8942000000,None,97852000000,25820000000,27064000000,268477000000,NaN,173144000000,100923000000,7469000000
22,2,2023-06-30,USD,411976000000,184257000000,34704000000,34704000000,2500000000,48688000000,227719000000,...,5247000000,None,59965000000,29906000000,17981000000,206223000000,NaN,118848000000,93718000000,7472000000
23,2,2022-06-30,USD,364840000000,169684000000,13931000000,13931000000,3742000000,44261000000,195156000000,...,2749000000,None,61270000000,27795000000,15526000000,166542000000,NaN,84281000000,86939000000,7540000000
24,2,2021-06-30,USD,333779000000,184406000000,14224000000,14224000000,2636000000,38043000000,149373000000,...,8072000000,None,67775000000,23897000000,13427000000,141988000000,NaN,57055000000,83111000000,7608000000
25,2,2020-06-30,USD,301311000000,181915000000,13576000000,13576000000,1895000000,32011000000,119396000000,...,3749000000,None,70998000000,20031000000,50915000000,118304000000,NaN,34566000000,80552000000,7683000000
26,2,2019-06-30,USD,286556000000,175552000000,11356000000,11356000000,2063000000,29524000000,111004000000,...,5516000000,None,78366000000,21846000000,47911000000,102330000000,NaN,24150000000,78520000000,7753000000
27,2,2018-06-30,USD,258848000000,169662000000,11946000000,11946000000,2662000000,26481000000,89186000000,...,3998000000,None,81808000000,16968000000,44859000000,82718000000,0,13682000000,71223000000,7794000000
28,2,2017-06-30,USD,241086000000,159851000000,7663000000,7663000000,2181000000,19792000000,81235000000,...,10121000000,None,86194000000,12914000000,17184000000,72394000000,0,2648000000,69315000000,7832000000
29,2,2016-06-30,USD,193694000000,139660000000,6510000000,6510000000,2251000000,18277000000,54034000000,...,12904000000,None,53687000000,12087000000,13640000000,71997000000,0,2282000000,68178000000,8013000000
30,2,2015-06-30,USD,174472000000,122797000000,5595000000,5595000000,2902000000,17908000000,51675000000,...,2499000000,None,35292000000,11743000000,13544000000,80083000000,0,9096000000,68465000000,8254000000
31,2,2014-06-30,USD,172384000000,114246000000,8669000000,8669000000,2660000000,19544000000,58138000000,...,23203000000,None,22645000000,12261000000,11594000000,89784000000,0,17710000000,68366000000,8399000000
32,2,2013-06-30,USD,142431000000,101466000000,3804000000,3804000000,1938000000,17486000000,40965000000,...,NaN,None,15600000000,8359000000,10000000000,78944000000,0,9895000000,67306000000,8470000000
33,2,2012-06-30,USD,121271000000,85084000000,6938000000,6938000000,1137000000,15780000000,36187000000,...,NaN,None,11944000000,7840000000,8208000000,66363000000,0,566000000,65797000000,8506000000
34,2,2011-06-30,USD,108704000000,74918000000,9610000000,9610000000,1372000000,14987000000,33786000000,...,NaN,None,17284000000,3492000000,8072000000,57083000000,0,-6332000000,63415000000,8593000000
35,2,2010-06-30,USD,86113000000,55676000000,5505000000,5505000000,740000000,13014000000,30437000000,...,NaN,None,5939000000,6396000000,7445000000,46175000000,0,-16681000000,62856000000,8927000000
36,2,2009-06-30,USD,77888000000,49280000000,6076000000,6076000000,717000000,11192000000,28608000000,...,NaN,None,5756000000,8707000000,NaN,39558000000,NaN,-22824000000,62382000000,8996000000
37,2,2008-06-30,USD,72793000000,43242000000,10339000000,10339000000,985000000,13589000000,29551000000,...,NaN,None,NaN,9207000000,NaN,36286000000,NaN,-27703000000,62849000000,9470000000
38,2,2006-06-30,USD,69597000000,49010000000,6714000000,6714000000,1478000000,9316000000,20587000000,...,NaN,None,NaN,10395000000,NaN,40104000000,NaN,-20130000000,59005000000,10531000000
39,2,2007-06-30,USD,63171000000,40168000000,6111000000,6111000000,1127000000,11338000000,23003000000,...,NaN,None,NaN,9728000000,NaN,31097000000,NaN,-31114000000,60557000000,9886000000
40,3,2006-12-31,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2044950000
41,3,2025-12-31,USD,137806000000,68642000000,16513000000,16513000000,12392000000,4576000000,69164000000,...,1569000000,None,8376000000,13279000000,1339000000,82137000000,NaN,39003000000,3000000,3528000000
42,3,2024-12-31,USD,122070000000,58360000000,16139000000,16139000000,12017000000,4418000000,63716000000,...,2343000000,None,13623000000,7556000000,1093000000,72913000000,NaN,35209000000,3000000,3498000000
43,3,2023-12-31,USD,106618000000,49616000000,16398000000,16398000000,13626000000,3508000000,57003000000,...,1975000000,None,9573000000,6328000000,876000000,62634000000,NaN,27882000000,3000000,3482750000
44,3,2022-12-31,USD,82338000000,40917000000,16253000000,16253000000,12839000000,2952000000,41421000000,...,1016000000,None,5748000000,5422000000,553000000,44704000000,NaN,12885000000,3000000,3475000000
45,3,2021-12-31,USD,62131000000,27100000000,17576000000,17576000000,5757000000,1913000000,35031000000,...,1088000000,None,8873000000,5719000000,10843000000,31015000000,NaN,331000000,1000000,3100522833
46,3,2020-12-31,USD,52148000000,26717000000,19384000000,19384000000,4101000000,1886000000,25434000000,...,2132000000,None,13279000000,2792000000,14170000000,22225000000,NaN,-5399000000,1000000,3249000000
47,3,2019-12-31,USD,34309000000,12103000000,6268000000,6268000000,3552000000,1324000000,22203000000,...,1785000000,None,14603000000,2383000000,408000000,6618000000,NaN,-6083000000,1000000,2655000000
48,3,2018-12-31,USD,29740000000,8307000000,3686000000,3686000000,3113000000,949000000,21435000000,...,2567699000,None,13828000000,2104886000,636409000,4923000000,NaN,-5318000000,173000,2559000000
49,3,2017-12-31,USD,28655372000,6570520000,3367914000,3367914000,2263537000,515381000,22084948000,...,896549000,None,12130863000,2250664000,2695386000,4237242000,0,-4974299000,169000,2486370000
50,3,2016-12-31,USD,22664076000,6259796000,3393216000,3393216000,2067454000,499142000,16400700000,...,1150147000,None,8801990000,1787648000,2507395000,4752911000,0,-2997237000,161000,2163180000
51,3,2015-12-31,USD,8067939000,2782006000,1196908000,1196908000,1277838000,168965000,5278030000,...,675212000,None,2897694000,458423000,1658717000,1083704000,0,-2322323000,131000,1923030000
52,3,2014-12-31,USD,5830667000,3180073000,1905713000,1905713000,953675000,226604000,2650550000,...,669295000,None,2530909000,424679000,661123000,911710000,0,-1433682000,126000,1868085000
53,3,2013-12-31,USD,2416930000,1265939000,845889000,845889000,340355000,49109000,1150966000,...,NaN,None,606878000,233338000,NaN,667120000,0,-1139620000,123000,1791315000
54,3,2012-12-31,USD,1114190000,524768000,201890000,201890000,268504000,26842000,589422000,...,NaN,None,466666000,30088000,25170000,124700000,0,-1065606000,115000,1610235000
55,3,2011-12-31,USD,713448000,372838000,255266000,255266000,50082000,9539000,340610000,...,NaN,None,280148000,31142000,14915000,224045000,0,-669392000,104000,1505832225
56,3,2010-12-31,USD,386082000,235886000,99558000,99558000,45182000,6710000,150196000,...,NaN,None,72107000,51700000,NaN,207048000,NaN,-414982000,95000,1427810175
57,3,2009-12-31,USD,130424000,100559000,69627000,69627000,23222000,3488000,29865000,...,NaN,None,1090000,40284000,NaN,-253523000,NaN,-260654000,7000,2044950000
58,3,2008-12-31,USD,51699000,31427000,9277000,9277000,16650000,3320000,20272000,...,NaN,None,55757000,67534000,NaN,-199714000,NaN,-204914000,7000,2044950000
59,3,2007-12-31,USD,34837000,22308000,17211000,17211000,2108000,59000,12529000,...,NaN,None,98000,45847000,NaN,-117846000,NaN,-122132000,18000,2044950000

### Group By / Having

In [57]:
stmt = (select(BalanceSheet.stock_id,
               func.max(BalanceSheet.total_assets).label("Max_total_assets"))
               .group_by(BalanceSheet.stock_id)
               .having(func.max(BalanceSheet.total_assets) > 300000000000)
               .order_by(asc("Max_total_assets"))
        )
pd.read_sql(stmt,engine)

   stock_id  Max_total_assets
0         1      375319000000
1         2      619003000000

### Subquery

In [72]:
# 1. Subquery for Balance Sheet Maximums
subq_assets = (
    select(
        BalanceSheet.stock_id, 
        func.max(BalanceSheet.total_assets).label("Max_Assets")
    )
    .group_by(BalanceSheet.stock_id)
    .subquery()
)

# 2. Subquery for Income Statement Maximums
subq_income = (
    select(
        IncomeStatement.stock_id, 
        func.max(IncomeStatement.net_income).label("Max_Net_Income")
    )
    .group_by(IncomeStatement.stock_id)
    .subquery()
)

# 3. Main query joining the two subqueries
stmt = (
    select(
        subq_assets.c.stock_id,
        subq_assets.c.Max_Assets,
        subq_income.c.Max_Net_Income
    )
    .join(subq_income, subq_assets.c.stock_id == subq_income.c.stock_id)
    .order_by(subq_assets.c.Max_Assets.desc())
)

df = pd.read_sql(stmt, engine)
df

   stock_id   Max_Assets  Max_Net_Income
0         2 619003000000    101832000000
1         1 375319000000    112010000000
2         3 137806000000     14974000000

### Common Table expressions

In [75]:
subq = (
    select(BalanceSheet.stock_id,BalanceSheet.fiscal_date_ending,BalanceSheet.total_assets, IncomeStatement.net_income)
    .join(
        IncomeStatement, 
        and_(
            BalanceSheet.stock_id == IncomeStatement.stock_id,
            BalanceSheet.fiscal_date_ending == IncomeStatement.fiscal_date_ending
        )
    ).cte()
)

print(subq)

SELECT alpha_vantage_db.balance_sheet.stock_id, alpha_vantage_db.balance_sheet.fiscal_date_ending, alpha_vantage_db.balance_sheet.total_assets, alpha_vantage_db.income_statement.net_income
FROM alpha_vantage_db.balance_sheet JOIN alpha_vantage_db.income_statement ON alpha_vantage_db.balance_sheet.stock_id = alpha_vantage_db.income_statement.stock_id AND alpha_vantage_db.balance_sheet.fiscal_date_ending = alpha_vantage_db.income_statement.fiscal_date_ending

In [135]:
stmt = select(
    subq.c.stock_id,
    subq.c.fiscal_date_ending,
    subq.c.net_income,
    subq.c.total_assets,
    # Example calculation: Return on Assets (Net Income / Total Assets)
    (subq.c.net_income  / subq.c.total_assets).label("return_on_assets")
).where(
    subq.c.total_assets > 0  # Filter to avoid division by zero
).order_by(
    subq.c.stock_id, 
    subq.c.fiscal_date_ending.desc()
)

In [136]:
df = pd.read_sql(stmt,engine)

In [139]:
df.head()

,stock_id,fiscal_date_ending,net_income,total_assets,return_on_assets
0,1,2025-09-30,112010000000.0000,359241000000.0000,0.3118
1,1,2024-09-30,93736000000.0000,364980000000.0000,0.2568
2,1,2023-09-30,96995000000.0000,352583000000.0000,0.2751
3,1,2022-09-30,99803000000.0000,352755000000.0000,0.2829
4,1,2021-09-30,94680000000.0000,351002000000.0000,0.2697