In [1]:
from massive import RESTClient
import pandas as pd

In [2]:
with open("key.txt") as file:
    API_key = file.read()

API_key = API_key.strip()
API_key

'kzwmu0jxgWk9U7pvaLpJIgg9uju9_Ofh'

In [3]:
client = RESTClient(api_key=API_key)

In [4]:
def query_ohlcv(ticker,multiplier=1, timespan="day", start="2024-05-05", end="2026-05-04",adjusted=True):
    # List Aggregates (Bars)
    aggs = []
    for a in client.list_aggs(ticker=ticker, multiplier=1, timespan=timespan, from_=start, to=end,adjusted=adjusted):
        aggs.append(a)
    df = pd.DataFrame(aggs)
    df['date'] = pd.to_datetime(df['timestamp'], unit='ms')
    df.to_csv(f"./ohlcv/{ticker}.csv")
    return df

In [5]:
ticker = "INTC"
df = query_ohlcv(ticker=ticker, multiplier=1, timespan="day", start="2024-05-05", end="2026-05-04",adjusted=True)
df.head()

,open,high,low,close,volume,vwap,timestamp,transactions,otc,date
0,31.115,31.200,30.730,30.97,36185572.0,30.9285,1714968000000,192226,None,2024-05-06 04:00:00
1,31.090,31.450,30.610,30.68,44683401.0,30.9452,1715054400000,211069,None,2024-05-07 04:00:00
2,30.000,30.150,29.730,30.00,63734597.0,29.9274,1715140800000,289849,None,2024-05-08 04:00:00
3,29.930,30.385,29.805,30.09,45003402.0,30.1078,1715227200000,198385,None,2024-05-09 04:00:00
4,30.330,30.455,29.840,29.85,42931290.0,30.0532,1715313600000,187944,None,2024-05-10 04:00:00

In [6]:
df.tail()

,open,high,low,close,volume,vwap,timestamp,transactions,otc,date
495,81.280,84.59,80.80,84.52,1.477735e+08,83.0546,1777348800000,883213,None,2026-04-28 04:00:00
496,86.135,94.95,85.87,94.75,2.350709e+08,92.1167,1777435200000,1400094,None,2026-04-29 04:00:00
497,95.600,95.69,91.50,94.48,1.605973e+08,93.7279,1777521600000,1015590,None,2026-04-30 04:00:00
498,93.200,100.45,92.61,99.62,1.585028e+08,98.6118,1777608000000,1062949,None,2026-05-01 04:00:00
499,99.180,99.82,95.60,95.78,1.192927e+08,97.5974,1777867200000,945584,None,2026-05-04 04:00:00