In [1]:
from dash import Dash, dcc, html, dash_table
import dash_bootstrap_components as dbc
from dash.dependencies import Output, Input
from dash.exceptions import PreventUpdate
from dash_bootstrap_templates import load_figure_template

import plotly.express as px
import pandas as pd
import numpy as np

In [2]:
from sqlalchemy import create_engine, MetaData,Table,Column, Integer, String,text,select
from sqlalchemy.orm import Session
from sqlalchemy.orm import DeclarativeBase

from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column

from sqlalchemy import and_
from sqlalchemy import func,desc,asc
from sqlalchemy import cast, Numeric,Float

import urllib.parse

In [3]:
with open("../querying_using_sqlalchemy/db_password.txt") as file:
    db_pw = file.read()

db_pw = db_pw.strip()

In [4]:
encoded_pw = urllib.parse.quote_plus(db_pw)
url = f"postgresql://postgres:{encoded_pw}@localhost:5432/postgres"
engine = create_engine(url)

In [5]:
# declarative base class
class Base(DeclarativeBase):
    pass

# Load the "Parent" first
class BalanceSheet(Base):
    __tablename__ = "balance_sheet"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

# Then load the "Children"
class IncomeStatement(Base):
    __tablename__ = "income_statement"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class CashFlow(Base):
    __tablename__ = "cash_flow"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class SharesOutstanding(Base):
    __tablename__ = "shares_outstanding"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Splits(Base):
    __tablename__ = "splits"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Dividends(Base):
    __tablename__ = "dividends"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Earnings(Base):
    __tablename__ = "earnings"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class EarningsEstimates(Base):
    __tablename__ = "earnings_estimates"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Overview(Base):
    __tablename__ = "overview"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Stock(Base):
    __tablename__ = "stock"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Currency(Base):
    __tablename__ = "currency"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class OHLCV(Base):
    __tablename__ = "ohlcv"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

In [6]:
stmt = (
            select(IncomeStatement,Stock)
            .join(
                Stock, 
                and_(
                    IncomeStatement.stock_id == Stock.stock_id
                )
            )
            #.order_by(IncomeStatement.report_type, IncomeStatement.fiscal_date_ending)
        )
income_df = pd.read_sql(stmt, engine)

In [7]:
calculated_column_names = (["calc_net_income","revenue_growth","gross_margin",
                            "operating_margin","net_margin","cogs_margin",
                            "expense_margin","tax_margin"
                            ])

In [104]:
df = income_df.query(f"report_type == 'ANNUAL' and ticker == 'AAPL'")
df = (df
    .assign(calc_net_income = lambda x: x["operating_income"] - x["income_tax_expense"],
            revenue_growth = lambda x: (x["total_revenue"] - x["total_revenue"].shift(1))/x["total_revenue"].shift(1)*100,
            gross_margin = lambda x: x["gross_profit"]/x["total_revenue"] * 100,
            operating_margin = lambda x: x["ebit"]/x["total_revenue"] * 100,
            net_margin = lambda x: (x["operating_income"] - x["income_tax_expense"])/x["total_revenue"] * 100,
            cogs_margin = lambda x: x["cost_of_revenue"]/x["total_revenue"] * 100,
            expense_margin = lambda x: x["operating_expenses"]/x["total_revenue"] * 100,
            tax_margin = lambda x: x["income_tax_expense"]/x["total_revenue"] * 100
            )
)

In [108]:
df = df.astype({"fiscal_date_ending":"datetime64[ns]"})

In [109]:
df

,stock_id,fiscal_date_ending,reported_currency,gross_profit,total_revenue,cost_of_revenue,cost_of_goods_and_services_sold,operating_income,selling_general_and_administrative,research_and_development,...,stock_id_1,ticker,calc_net_income,revenue_growth,gross_margin,operating_margin,net_margin,cogs_margin,expense_margin,tax_margin
0,1,2025-09-30,USD,1.952010e+11,4.161610e+11,2.209600e+11,2.209600e+11,1.330500e+11,8.077000e+09,3.455000e+10,...,1,AAPL,1.123310e+11,NaN,46.905164,31.893666,26.992198,53.094836,14.934364,4.978602
1,1,2024-09-30,USD,1.806830e+11,3.910350e+11,2.103520e+11,2.103520e+11,1.232160e+11,2.609700e+10,3.137000e+10,...,1,AAPL,9.346700e+10,-6.037567,46.206350,31.510223,23.902464,53.793650,14.696127,7.607759
2,1,2023-09-30,USD,1.691480e+11,3.832850e+11,2.141370e+11,2.141370e+11,1.143010e+11,2.493200e+10,2.991500e+10,...,1,AAPL,9.756000e+10,-1.981920,44.131130,29.821412,25.453644,55.868870,14.309717,4.367768
3,1,2022-09-30,USD,1.707820e+11,3.943280e+11,2.235460e+11,2.235460e+11,1.194370e+11,2.509400e+10,2.625100e+10,...,1,AAPL,1.001370e+11,2.881146,43.309631,30.288744,25.394342,56.690369,13.078706,4.894403
4,1,2021-09-30,USD,1.528360e+11,3.658170e+11,2.129810e+11,2.129810e+11,1.089490e+11,2.197300e+10,2.191400e+10,...,1,AAPL,9.442200e+10,-7.230275,41.779360,30.575944,25.811266,58.220640,11.996982,3.971111
5,1,2020-09-30,USD,1.049560e+11,2.745150e+11,1.695590e+11,1.695590e+11,6.628800e+10,1.991600e+10,1.875200e+10,...,1,AAPL,5.660800e+10,-24.958381,38.233248,25.486403,20.621095,61.766752,14.085933,3.526219
6,1,2019-09-30,USD,9.839200e+10,2.601740e+11,1.617820e+11,1.617820e+11,6.393000e+10,1.824500e+10,1.621700e+10,...,1,AAPL,5.344900e+10,-5.224123,37.817768,26.641017,20.543559,62.182232,13.245751,4.028458
7,1,2018-09-30,USD,1.018390e+11,2.655950e+11,1.637560e+11,1.637560e+11,7.089800e+10,1.670500e+10,1.423600e+10,...,1,AAPL,5.752600e+10,2.083606,38.343719,28.668838,21.659293,61.656281,11.649692,5.034733
8,1,2017-09-30,USD,8.818600e+10,2.292340e+11,1.410480e+11,1.410480e+11,6.134400e+10,1.526100e+10,1.158100e+10,...,1,AAPL,4.560600e+10,-13.690393,38.469860,28.971270,19.894955,61.530140,11.709432,6.865474
9,1,2016-09-30,USD,8.426300e+10,2.156390e+11,1.313760e+11,1.313760e+11,6.002400e+10,1.419400e+10,1.004500e+10,...,1,AAPL,4.433900e+10,-5.930621,39.075956,29.135731,20.561679,60.924044,11.240546,7.273731
10,1,2015-09-30,USD,9.362600e+10,2.337150e+11,1.400890e+11,1.400890e+11,7.123000e+10,1.432900e+10,8.067000e+09,...,1,AAPL,5.210900e+10,8.382528,40.059902,31.340736,22.295959,59.940098,9.582611,8.181332
11,1,2014-09-30,USD,7.053700e+10,1.827950e+11,1.122580e+11,1.122580e+11,5.250300e+10,1.199300e+10,6.041000e+09,...,1,AAPL,3.853000e+10,-21.787219,38.588036,29.468530,21.078257,61.411964,9.865697,7.644082
12,1,2013-09-30,USD,6.430400e+10,1.709100e+11,1.066060e+11,1.066060e+11,4.899900e+10,9.730000e+09,4.475000e+09,...,1,AAPL,3.588100e+10,-6.501819,37.624481,29.425429,20.994090,62.375519,8.955006,7.675385
13,1,2012-09-30,USD,6.866200e+10,1.565080e+11,8.784600e+10,8.784600e+10,5.524100e+10,9.040000e+09,3.381000e+09,...,1,AAPL,4.121100e+10,-8.426657,43.871240,35.629489,26.331561,56.128760,8.575280,8.964398
14,1,2011-09-30,USD,4.381800e+10,1.082490e+11,6.443100e+10,6.443100e+10,3.379000e+10,7.599000e+09,2.429000e+09,...,1,AAPL,2.550700e+10,-30.834846,40.478896,31.598444,23.563266,59.521104,9.263827,7.651803
15,1,2010-09-30,USD,2.568400e+10,6.522500e+10,3.954100e+10,3.954100e+10,1.838500e+10,5.517000e+09,1.782000e+09,...,1,AAPL,1.385800e+10,-39.745402,39.377539,28.187045,21.246455,60.622461,11.190494,6.940590
16,1,2009-09-30,USD,1.722200e+10,4.290500e+10,2.568300e+10,2.568300e+10,1.174000e+10,4.149000e+09,1.333000e+09,...,1,AAPL,7.909000e+09,-34.220008,40.139844,27.362778,18.433749,59.860156,12.777066,8.929029
17,1,2008-09-30,USD,1.114500e+10,3.247900e+10,2.133400e+10,2.133400e+10,6.275000e+09,3.761000e+09,1.109000e+09,...,1,AAPL,4.214000e+09,-24.300198,34.314480,21.229102,12.974537,65.685520,14.994304,6.345639
18,1,2007-09-30,USD,8.154000e+09,2.400600e+10,1.585200e+10,1.585200e+10,4.409000e+09,2.963000e+09,7.820000e+08,...,1,AAPL,2.897000e+09,-26.087626,33.966508,18.357911,12.067816,66.033492,15.600267,6.298425
19,1,2006-09-30,USD,5.598000e+09,1.931500e+10,1.371700e+10,1.371700e+10,2.453000e+09,2.433000e+09,7.120000e+08,...,1,AAPL,1.624000e+09,-19.540948,28.982656,12.699974,8.407973,71.017344,16.282682,4.292001

In [110]:
df[df.fiscal_date_ending == '2025-09-30'][["calc_net_income","income_tax_expense","operating_expenses","cost_of_revenue"]].T

                               0
calc_net_income     1.123310e+11
income_tax_expense  2.071900e+10
operating_expenses  6.215100e+10
cost_of_revenue     2.209600e+11

In [111]:
plot_df = pd.DataFrame(df[df.fiscal_date_ending == '2025-09-30'][["calc_net_income","income_tax_expense","operating_expenses","cost_of_revenue"]].T)
plot_df.reset_index(inplace=True)
plot_df = plot_df.rename(columns={"index":"col1",0:"col2"})
plot_df.sort_values(by="col2",inplace=True,ascending=False)
plot_df

                 col1          col2
3     cost_of_revenue  2.209600e+11
0     calc_net_income  1.123310e+11
2  operating_expenses  6.215100e+10
1  income_tax_expense  2.071900e+10

In [11]:
px.pie(plot_df, values="col2", names="col1", title='Apples Revenue Composition',
       hole=0.25)

In [113]:
load_figure_template("morph")

dbc_css = "https://cdn.jsdelivr.net/gh/AnnMarieW/dash-bootstrap-templates/dbc.min.css"

app = Dash(__name__,external_stylesheets=[dbc.themes.MORPH,dbc_css])

app.layout = html.Div([
                        dcc.Tabs([
                            dcc.Tab(label="Financial Statements",
                                    children=[
                                        dbc.Row([
                                            dcc.Markdown(id="markdown_title",
                                                         style={'textAlign':'center',
                                                                'fontSize':30,
                                                                'fontWeight':'bold',
                                                                'fontFamily':'sans-serif'})
                                                ]),
                                        dbc.Row([
                                                dbc.Col([
                                                            html.P("Select A Stock :"),
                                                            html.Br(),
                                                            dcc.Dropdown(id="stock_selector",
                                                                        options=income_df["ticker"].unique(),
                                                                        value="AAPL",
                                                                        className="dbc"),
                                                            html.P("Select A Value to Plot :"),
                                                            html.Br(),
                                                            dcc.Dropdown(id="income_column_selector",
                                                                        options=list(income_df.select_dtypes(include='number').columns[1:-1]) + calculated_column_names,
                                                                        value="total_revenue",
                                                                        className="dbc")
                                                    ],width=2),
                                                dbc.Col([
                                                            dcc.Graph(id="first_plot")
                                                    ]),
                                                dbc.Col([
                                                            dcc.Markdown(id="debug_md"),
                                                            dcc.Graph(id="second_plot")#hoverData={'points': [{'customdata': ['2025-12-31']}]}
                                                    ],width=4)
                                                ])
                                        ])
                                    ])
                    ],className="dbc")

@app.callback(
    Output("markdown_title","children"),
    Output("first_plot","figure"),
    Input("stock_selector","value"),
    Input("income_column_selector","value")
)
def plot_tab1(ticker,column_name):
    if not ticker:
        raise PreventUpdate
    
    df = income_df.query(f"report_type == 'ANNUAL' and ticker == '{ticker}'")
    df = (df
        .assign(calc_net_income = lambda x: x["operating_income"] - x["income_tax_expense"],
                revenue_growth = lambda x: (x["total_revenue"] - x["total_revenue"].shift(1))/x["total_revenue"].shift(1)*100,
                gross_margin = lambda x: x["gross_profit"]/x["total_revenue"] * 100,
                operating_margin = lambda x: x["ebit"]/x["total_revenue"] * 100,
                net_margin = lambda x: (x["operating_income"] - x["income_tax_expense"])/x["total_revenue"] * 100,
                cogs_margin = lambda x: x["cost_of_revenue"]/x["total_revenue"] * 100,
                expense_margin = lambda x: x["operating_expenses"]/x["total_revenue"] * 100,
                tax_margin = lambda x: x["income_tax_expense"]/x["total_revenue"] * 100
                )
    )
    
    fig = px.bar(
                df,
                "fiscal_date_ending",
                column_name,
                title= f"{column_name.upper()} over the years",
                custom_data = ["fiscal_date_ending"]
    )
    
    #fig = px.line(df, x='fiscal_date_ending', y=column_name,markers=True,custom_data = ["fiscal_date_ending"])
    dates = pd.to_datetime(df["fiscal_date_ending"])
    
    fig.update_xaxes(
        type="date",
        tickmode="array",
        tickvals=df["fiscal_date_ending"],
        tickformat="%Y",
        range=[dates.min() - pd.DateOffset(months=6), dates.max() + pd.DateOffset(months=6)]
    )
    title =  f"Income Statement Plot of {ticker}"
    return title,fig

@app.callback(
    Output("second_plot","figure"),
    Output("debug_md","children"),
    Input("first_plot","hoverData"),
    Input("stock_selector","value")
)
def plot_tab11(hoverData,ticker):
    if not hoverData or not ticker:
        raise PreventUpdate
    df = income_df.query(f"report_type == 'ANNUAL' and ticker == '{ticker}'")
    df = df.astype({"fiscal_date_ending":"datetime64[ns]"})
    df = (df
        .assign(calc_net_income = lambda x: x["operating_income"] - x["income_tax_expense"],
                revenue_growth = lambda x: (x["total_revenue"] - x["total_revenue"].shift(1))/x["total_revenue"].shift(1)*100,
                gross_margin = lambda x: x["gross_profit"]/x["total_revenue"] * 100,
                operating_margin = lambda x: x["ebit"]/x["total_revenue"] * 100,
                net_margin = lambda x: (x["operating_income"] - x["income_tax_expense"])/x["total_revenue"] * 100,
                cogs_margin = lambda x: x["cost_of_revenue"]/x["total_revenue"] * 100,
                expense_margin = lambda x: x["operating_expenses"]/x["total_revenue"] * 100,
                tax_margin = lambda x: x["income_tax_expense"]/x["total_revenue"] * 100
                )
    )
    year = pd.to_datetime(hoverData["points"][0]["customdata"][0])
    plot_df = pd.DataFrame(df[df.fiscal_date_ending == year][["calc_net_income","income_tax_expense","operating_expenses","cost_of_revenue"]].T)
    plot_df.reset_index(inplace=True)
    plot_df.columns = ["col1", "col2"]
    plot_df.sort_values(by="col2",inplace=True,ascending=False)
    fig = px.pie(plot_df, values="col2", names="col1", title='Revenue Composition',hole=0.25)
    return fig,f"selected date is {year}"

if __name__ == "__main__":
    app.run(debug=True)#jupyter_mode="external"