In [19]:
from dash import Dash, dcc, html, dash_table
import dash_bootstrap_components as dbc
from dash.dependencies import Output, Input
from dash.exceptions import PreventUpdate
from dash_bootstrap_templates import load_figure_template

import plotly.express as px
import pandas as pd
import numpy as np

In [20]:
from sqlalchemy import create_engine, MetaData,Table,Column, Integer, String,text,select
from sqlalchemy.orm import Session
from sqlalchemy.orm import DeclarativeBase

from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column

from sqlalchemy import and_
from sqlalchemy import func,desc,asc
from sqlalchemy import cast, Numeric,Float

import urllib.parse

In [21]:
with open("../querying_using_sqlalchemy/db_password.txt") as file:
    db_pw = file.read()

db_pw = db_pw.strip()

In [22]:
encoded_pw = urllib.parse.quote_plus(db_pw)
url = f"postgresql://postgres:{encoded_pw}@localhost:5432/postgres"
engine = create_engine(url)

In [23]:
# declarative base class
class Base(DeclarativeBase):
    pass

# Load the "Parent" first
class BalanceSheet(Base):
    __tablename__ = "balance_sheet"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

# Then load the "Children"
class IncomeStatement(Base):
    __tablename__ = "income_statement"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class CashFlow(Base):
    __tablename__ = "cash_flow"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class SharesOutstanding(Base):
    __tablename__ = "shares_outstanding"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Splits(Base):
    __tablename__ = "splits"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Dividends(Base):
    __tablename__ = "dividends"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Earnings(Base):
    __tablename__ = "earnings"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class EarningsEstimates(Base):
    __tablename__ = "earnings_estimates"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Overview(Base):
    __tablename__ = "overview"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Stock(Base):
    __tablename__ = "stock"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Currency(Base):
    __tablename__ = "currency"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class OHLCV(Base):
    __tablename__ = "ohlcv"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

In [24]:
stmt = (
            select(IncomeStatement,Stock)
            .join(
                Stock, 
                and_(
                    IncomeStatement.stock_id == Stock.stock_id
                )
            )
            #.order_by(IncomeStatement.report_type, IncomeStatement.fiscal_date_ending)
        )
income_df = pd.read_sql(stmt, engine)

In [25]:
income_df.to_csv("income_statements.csv", index=False)

In [26]:
income_df_csv = pd.read_csv("income_statements.csv")

In [27]:
calculated_column_names = (["calc_net_income","revenue_growth","gross_margin",
                            "operating_margin","net_margin","cogs_margin",
                            "expense_margin","tax_margin"
                            ])

In [42]:
tickers = ['AAPL','TSLA']
df = (income_df_csv.query(f"report_type == 'ANNUAL' and ticker in @tickers")
      .sort_values(by=['stock_id','fiscal_date_ending'],ascending=True))

In [43]:
df

,stock_id,fiscal_date_ending,reported_currency,gross_profit,total_revenue,cost_of_revenue,cost_of_goods_and_services_sold,operating_income,selling_general_and_administrative,research_and_development,...,income_tax_expense,interest_and_debt_expense,net_income_from_continuing_operations,comprehensive_income_net_of_tax,ebit,ebitda,net_income,report_type,stock_id_1,ticker
19,1,2006-09-30,USD,5.598000e+09,1.931500e+10,1.371700e+10,1.371700e+10,2.453000e+09,2.433000e+09,7.120000e+08,...,8.290000e+08,NaN,NaN,NaN,2.453000e+09,2.678000e+09,1.989000e+09,ANNUAL,1,AAPL
18,1,2007-09-30,USD,8.154000e+09,2.400600e+10,1.585200e+10,1.585200e+10,4.409000e+09,2.963000e+09,7.820000e+08,...,1.512000e+09,NaN,NaN,NaN,4.407000e+09,4.724000e+09,3.495000e+09,ANNUAL,1,AAPL
17,1,2008-09-30,USD,1.114500e+10,3.247900e+10,2.133400e+10,2.133400e+10,6.275000e+09,3.761000e+09,1.109000e+09,...,2.061000e+09,NaN,NaN,NaN,6.895000e+09,7.304000e+09,4.834000e+09,ANNUAL,1,AAPL
16,1,2009-09-30,USD,1.722200e+10,4.290500e+10,2.568300e+10,2.568300e+10,1.174000e+10,4.149000e+09,1.333000e+09,...,3.831000e+09,NaN,8.235000e+09,NaN,1.174000e+10,1.247400e+10,8.235000e+09,ANNUAL,1,AAPL
15,1,2010-09-30,USD,2.568400e+10,6.522500e+10,3.954100e+10,3.954100e+10,1.838500e+10,5.517000e+09,1.782000e+09,...,4.527000e+09,NaN,1.401300e+10,NaN,1.838500e+10,1.941200e+10,1.401300e+10,ANNUAL,1,AAPL
14,1,2011-09-30,USD,4.381800e+10,1.082490e+11,6.443100e+10,6.443100e+10,3.379000e+10,7.599000e+09,2.429000e+09,...,8.283000e+09,NaN,2.592200e+10,NaN,3.420500e+10,3.601900e+10,2.592200e+10,ANNUAL,1,AAPL
13,1,2012-09-30,USD,6.866200e+10,1.565080e+11,8.784600e+10,8.784600e+10,5.524100e+10,9.040000e+09,3.381000e+09,...,1.403000e+10,NaN,4.173300e+10,NaN,5.576300e+10,5.904000e+10,4.173300e+10,ANNUAL,1,AAPL
12,1,2013-09-30,USD,6.430400e+10,1.709100e+11,1.066060e+11,1.066060e+11,4.899900e+10,9.730000e+09,4.475000e+09,...,1.311800e+10,NaN,3.703700e+10,NaN,5.029100e+10,5.704800e+10,3.703700e+10,ANNUAL,1,AAPL
11,1,2014-09-30,USD,7.053700e+10,1.827950e+11,1.122580e+11,1.122580e+11,5.250300e+10,1.199300e+10,6.041000e+09,...,1.397300e+10,NaN,3.951000e+10,NaN,5.386700e+10,6.181300e+10,3.951000e+10,ANNUAL,1,AAPL
10,1,2015-09-30,USD,9.362600e+10,2.337150e+11,1.400890e+11,1.400890e+11,7.123000e+10,1.432900e+10,8.067000e+09,...,1.912100e+10,NaN,5.339400e+10,NaN,7.324800e+10,8.450500e+10,5.339400e+10,ANNUAL,1,AAPL
9,1,2016-09-30,USD,8.426300e+10,2.156390e+11,1.313760e+11,1.313760e+11,6.002400e+10,1.419400e+10,1.004500e+10,...,1.568500e+10,NaN,4.568700e+10,NaN,6.282800e+10,7.333300e+10,4.568700e+10,ANNUAL,1,AAPL
8,1,2017-09-30,USD,8.818600e+10,2.292340e+11,1.410480e+11,1.410480e+11,6.134400e+10,1.526100e+10,1.158100e+10,...,1.573800e+10,NaN,4.835100e+10,NaN,6.641200e+10,7.656900e+10,4.835100e+10,ANNUAL,1,AAPL
7,1,2018-09-30,USD,1.018390e+11,2.655950e+11,1.637560e+11,1.637560e+11,7.089800e+10,1.670500e+10,1.423600e+10,...,1.337200e+10,NaN,5.953100e+10,NaN,7.614300e+10,8.704600e+10,5.953100e+10,ANNUAL,1,AAPL
6,1,2019-09-30,USD,9.839200e+10,2.601740e+11,1.617820e+11,1.617820e+11,6.393000e+10,1.824500e+10,1.621700e+10,...,1.048100e+10,NaN,5.525600e+10,NaN,6.931300e+10,8.186000e+10,5.525600e+10,ANNUAL,1,AAPL
5,1,2020-09-30,USD,1.049560e+11,2.745150e+11,1.695590e+11,1.695590e+11,6.628800e+10,1.991600e+10,1.875200e+10,...,9.680000e+09,NaN,5.741100e+10,NaN,6.996400e+10,8.102000e+10,5.741100e+10,ANNUAL,1,AAPL
4,1,2021-09-30,USD,1.528360e+11,3.658170e+11,2.129810e+11,2.129810e+11,1.089490e+11,2.197300e+10,2.191400e+10,...,1.452700e+10,NaN,9.468000e+10,NaN,1.118520e+11,1.231360e+11,9.468000e+10,ANNUAL,1,AAPL
3,1,2022-09-30,USD,1.707820e+11,3.943280e+11,2.235460e+11,2.235460e+11,1.194370e+11,2.509400e+10,2.625100e+10,...,1.930000e+10,NaN,9.980300e+10,NaN,1.194370e+11,1.305410e+11,9.980300e+10,ANNUAL,1,AAPL
2,1,2023-09-30,USD,1.691480e+11,3.832850e+11,2.141370e+11,2.141370e+11,1.143010e+11,2.493200e+10,2.991500e+10,...,1.674100e+10,NaN,9.699500e+10,NaN,1.143010e+11,1.258200e+11,9.699500e+10,ANNUAL,1,AAPL
1,1,2024-09-30,USD,1.806830e+11,3.910350e+11,2.103520e+11,2.103520e+11,1.232160e+11,2.609700e+10,3.137000e+10,...,2.974900e+10,NaN,9.373600e+10,NaN,1.232160e+11,1.346610e+11,9.373600e+10,ANNUAL,1,AAPL
0,1,2025-09-30,USD,1.952010e+11,4.161610e+11,2.209600e+11,2.209600e+11,1.330500e+11,8.077000e+09,3.455000e+10,...,2.071900e+10,NaN,1.120100e+11,NaN,1.327290e+11,1.444270e+11,1.120100e+11,ANNUAL,1,AAPL
38,2,2006-12-31,USD,-6.150000e+05,NaN,6.150000e+05,6.150000e+05,-3.043100e+07,NaN,2.499500e+07,...,1.000000e+05,NaN,NaN,NaN,-2.943400e+07,-2.881900e+07,-2.995700e+07,ANNUAL,2,TSLA
37,2,2007-12-31,USD,6.400000e+04,7.300000e+04,9.000000e+03,9.000000e+03,-7.993300e+07,NaN,6.275300e+07,...,1.100000e+05,NaN,NaN,NaN,-7.804700e+07,-7.515200e+07,-7.815700e+07,ANNUAL,2,TSLA
36,2,2008-12-31,USD,-1.141000e+06,1.474200e+07,1.588300e+07,1.588300e+07,-7.850400e+07,NaN,5.371400e+07,...,9.700000e+04,NaN,NaN,NaN,-7.893800e+07,-7.478100e+07,-8.278200e+07,ANNUAL,2,TSLA
35,2,2009-12-31,USD,9.535000e+06,1.119430e+08,1.024080e+08,1.024080e+08,-5.189700e+07,NaN,1.928200e+07,...,2.600000e+04,NaN,NaN,NaN,-5.318300e+07,-4.624300e+07,-5.574000e+07,ANNUAL,2,TSLA
34,2,2010-12-31,USD,3.073100e+07,1.167440e+08,8.601300e+07,8.601300e+07,-1.468380e+08,8.457300e+07,9.299600e+07,...,1.730000e+05,NaN,NaN,NaN,-1.531630e+08,-1.425400e+08,-1.543280e+08,ANNUAL,2,TSLA
33,2,2011-12-31,USD,6.159500e+07,2.042420e+08,1.426470e+08,1.426470e+08,-2.514880e+08,1.041020e+08,2.089810e+08,...,4.890000e+05,NaN,NaN,NaN,-2.538790e+08,-2.369600e+08,-2.544110e+08,ANNUAL,2,TSLA
32,2,2012-12-31,USD,3.006700e+07,4.132560e+08,3.831890e+08,3.831890e+08,-3.942830e+08,1.464720e+08,2.739780e+08,...,1.360000e+05,NaN,NaN,NaN,-3.958230e+08,-3.669980e+08,-3.962130e+08,ANNUAL,2,TSLA
31,2,2013-12-31,USD,4.562620e+08,2.013496e+09,1.557234e+09,1.557234e+09,-6.128300e+07,2.765690e+08,2.319760e+08,...,2.588000e+06,NaN,NaN,NaN,-3.849200e+07,6.759100e+07,-7.401400e+07,ANNUAL,2,TSLA
30,2,2014-12-31,USD,8.816710e+08,3.198356e+09,2.316685e+09,2.316685e+09,-1.866890e+08,5.547600e+08,4.647000e+08,...,9.404000e+06,NaN,NaN,NaN,-1.837500e+08,4.818100e+07,-2.940400e+08,ANNUAL,2,TSLA
29,2,2015-12-31,USD,9.235030e+08,4.046025e+09,3.122522e+09,3.122522e+09,-7.166290e+08,8.639320e+08,7.179000e+08,...,1.303900e+07,NaN,NaN,NaN,-7.567730e+08,-3.341830e+08,-8.886630e+08,ANNUAL,2,TSLA
28,2,2016-12-31,USD,1.599257e+09,7.000132e+09,5.400875e+09,5.400875e+09,-6.673400e+08,1.384189e+09,8.344080e+08,...,2.669800e+07,NaN,NaN,NaN,-5.475380e+08,3.995610e+08,-6.749140e+08,ANNUAL,2,TSLA
27,2,2017-12-31,USD,2.223000e+09,1.175900e+10,9.536000e+09,9.536000e+09,-1.632000e+09,2.439500e+09,1.378000e+09,...,3.200000e+07,NaN,-2.240578e+09,NaN,-1.738000e+09,-1.020000e+08,-1.962000e+09,ANNUAL,2,TSLA
26,2,2018-12-31,USD,4.042021e+09,2.146127e+10,1.741925e+10,1.741925e+10,-3.880000e+08,2.835000e+09,1.460370e+09,...,5.800000e+07,NaN,-1.062582e+09,NaN,-3.420000e+08,1.559000e+09,-9.760000e+08,ANNUAL,2,TSLA
25,2,2019-12-31,USD,4.069000e+09,2.457800e+10,2.050900e+10,2.050900e+10,-6.900000e+07,2.646000e+09,1.343000e+09,...,1.100000e+08,NaN,-7.750000e+08,NaN,1.800000e+07,2.172000e+09,-8.620000e+08,ANNUAL,2,TSLA
24,2,2020-12-31,USD,6.630000e+09,3.153600e+10,2.490600e+10,2.490600e+10,1.994000e+09,3.145000e+09,1.491000e+09,...,2.920000e+08,NaN,8.620000e+08,NaN,1.902000e+09,4.224000e+09,7.210000e+08,ANNUAL,2,TSLA
23,2,2021-12-31,USD,1.360600e+10,5.382300e+10,4.021700e+10,4.021700e+10,6.687000e+09,4.517000e+09,2.593000e+09,...,6.990000e+08,NaN,5.644000e+09,NaN,6.687000e+09,9.598000e+09,5.644000e+09,ANNUAL,2,TSLA
22,2,2022-12-31,USD,2.085300e+10,8.146200e+10,6.060900e+10,6.060900e+10,1.365600e+10,3.946000e+09,3.075000e+09,...,1.132000e+09,NaN,1.258700e+10,NaN,1.429000e+10,1.783300e+10,1.258700e+10,ANNUAL,2,TSLA
21,2,2023-12-31,USD,1.766000e+10,9.677300e+10,7.911300e+10,7.911300e+10,8.891000e+09,4.800000e+09,3.969000e+09,...,-5.001000e+09,NaN,1.497400e+10,NaN,1.012900e+10,1.479600e+10,1.497400e+10,ANNUAL,2,TSLA
20,2,2024-12-31,USD,1.745000e+10,9.769000e+10,8.024000e+10,8.024000e+10,7.076000e+09,5.150000e+09,4.540000e+09,...,1.837000e+09,NaN,7.153000e+09,NaN,9.340000e+09,1.470800e+10,7.130000e+09,ANNUAL,2,TSLA
9938,2,2025-12-31,USD,1.709400e+10,9.482700e+10,7.773300e+10,7.773300e+10,4.355000e+09,5.834000e+09,6.411000e+09,...,1.423000e+09,NaN,3.855000e+09,NaN,5.616000e+09,1.176400e+10,3.794000e+09,ANNUAL,2,TSLA

In [28]:
stmt = (
            select(BalanceSheet,Stock)
            .join(
                Stock, 
                and_(
                    BalanceSheet.stock_id == Stock.stock_id
                )
            )
            #.order_by(IncomeStatement.report_type, IncomeStatement.fiscal_date_ending)
        )
balance_df = pd.read_sql(stmt, engine)
balance_df.to_csv("balance_sheet.csv", index=False)

In [29]:
calculated_column_names_bal = (["current_ratio","liabilities_to_equity","return_on_equity"])

In [30]:
bal_df_csv = pd.read_csv("balance_sheet.csv")

In [46]:
stmt = (
            select(CashFlow,Stock)
            .join(
                Stock, 
                and_(
                    CashFlow.stock_id == Stock.stock_id
                )
            )
        )
cash_df = pd.read_sql(stmt, engine)
cash_df.to_csv("cashflow.csv", index=False)

In [47]:
calculated_column_names_cash = (["free_cash_flow"])

In [48]:
cash_df_csv = pd.read_csv("cashflow.csv")

In [52]:
cash_df_csv.head()

,stock_id,fiscal_date_ending,reported_currency,operating_cashflow,payments_for_operating_activities,proceeds_from_operating_activities,change_in_operating_liabilities,change_in_operating_assets,depreciation_depletion_and_amortization,capital_expenditures,...,proceeds_from_issuance_of_preferred_stock,proceeds_from_repurchase_of_equity,proceeds_from_sale_of_treasury_stock,stock_based_compensation,change_in_cash_and_cash_equivalents,change_in_exchange_rate,net_income,report_type,stock_id_1,ticker
0,1,2025-09-30,USD,1.114820e+11,NaN,NaN,NaN,NaN,1.169800e+10,1.271500e+10,...,NaN,-9.071100e+10,NaN,1.286300e+10,NaN,NaN,1.120100e+11,ANNUAL,1,AAPL
1,1,2024-09-30,USD,1.182540e+11,NaN,NaN,NaN,NaN,1.144500e+10,9.447000e+09,...,NaN,-9.494900e+10,NaN,1.168800e+10,NaN,NaN,9.373600e+10,ANNUAL,1,AAPL
2,1,2023-09-30,USD,1.105430e+11,NaN,NaN,NaN,NaN,1.151900e+10,1.095900e+10,...,NaN,-7.755000e+10,NaN,1.083300e+10,5.760000e+09,NaN,9.699500e+10,ANNUAL,1,AAPL
3,1,2022-09-30,USD,1.221510e+11,NaN,NaN,NaN,NaN,1.110400e+10,1.070800e+10,...,NaN,-8.940200e+10,NaN,9.038000e+09,-1.095200e+10,NaN,9.980300e+10,ANNUAL,1,AAPL
4,1,2021-09-30,USD,1.040380e+11,NaN,NaN,NaN,NaN,1.128400e+10,1.108500e+10,...,NaN,-8.597100e+10,NaN,7.906000e+09,-3.860000e+09,NaN,9.468000e+10,ANNUAL,1,AAPL

In [63]:
template_name = "superhero"
load_figure_template(template_name)

dbc_css = "https://cdn.jsdelivr.net/gh/AnnMarieW/dash-bootstrap-templates/dbc.min.css"

app = Dash(__name__,external_stylesheets=[dbc.themes.SUPERHERO,dbc_css],suppress_callback_exceptions=True)

app.layout = html.Div([
                        dcc.Tabs([
                            dcc.Tab(label="Income Statement",
                                    children=[
                                        dbc.Row([
                                            dcc.Markdown(id="markdown_title",
                                                         style={'textAlign':'center',
                                                                'fontSize':30,
                                                                'fontWeight':'bold',
                                                                'fontFamily':'sans-serif'})
                                                ]),
                                        dbc.Row([
                                                dbc.Col([   
                                                            html.P("Select your comparison type :"),
                                                            dcc.RadioItems(id="tab1_OutputPicker",
                                                                           options = ["stock","component"],
                                                                           value="stock"),
                                                            html.P("Select one or more Stocks :"),
                                                            dcc.Dropdown(id="tab1_stock_dropdown",
                                                                        options=income_df_csv["ticker"].unique(),
                                                                        value="AAPL"),
                                                            html.Br(),          
                                                            html.P("Select a Column to Plot :"),
                                                            dcc.Dropdown(id="tab1_comp_dropdown",
                                                                        options=list(income_df_csv.select_dtypes(include='number').columns[1:-1]) + calculated_column_names,
                                                                        value="total_revenue"),
                                                            html.Br(), 
                                                            html.P("Select plot type :"),
                                                            dcc.RadioItems(id="graph_picker",
                                                                           options = ["bar","line"],
                                                                           value="bar",
                                                                           inline=True),
                                                            html.Br(), 
                                                            html.P("Last x Years:"),
                                                            dcc.RadioItems(id="year_picker",
                                                                           options = [5,10,15,20],
                                                                           value=5,
                                                                           inline=True),
                                                            html.P("Report type:"),
                                                            dcc.RadioItems(id="income_reporttype",
                                                                           options = ["ANNUAL","QUARTERLY"],
                                                                           value="ANNUAL",
                                                                           inline=True),
                                                    ],width=2),
                                                dbc.Col([
                                                            dcc.Graph(id="first_plot")#html.Div(id="first_plot")#
                                                    ]),
                                                dbc.Col([
                                                            #dcc.Markdown(id="debug_md"),
                                                            dcc.Graph(id="second_plot")
                                                    ],width=4)
                                                ])
                                        ]),
                            dcc.Tab(label="Balance Sheet",
                                    children=[
                                        dbc.Row([
                                            dcc.Markdown(id="bal_markdown_title",
                                                         style={'textAlign':'center',
                                                                'fontSize':30,
                                                                'fontWeight':'bold',
                                                                'fontFamily':'sans-serif'})
                                                ]),
                                        dbc.Row([
                                                dbc.Col([
                                                            html.P("Select your comparison type :"),
                                                            dcc.RadioItems(id="tab2_OutputPicker",
                                                                           options = ["stock","component"],
                                                                           value="stock"),
                                                            html.P("Select one or more Stocks :"),
                                                            dcc.Dropdown(id="tab2_stock_dropdown",
                                                                        options=bal_df_csv["ticker"].unique()),
                                                            html.Br(),          
                                                            html.P("Select a Component to Plot :"),
                                                            dcc.Dropdown(id="tab2_comp_dropdown",
                                                                         options=list(bal_df_csv.select_dtypes(include='number').columns[1:-1]) + calculated_column_names_bal),
                                                            html.Br(), 
                                                            html.P("Select plot type :"),
                                                            dcc.RadioItems(id="bal_graph_picker",
                                                                           options = ["bar","line"],
                                                                           value="bar",
                                                                           inline=True),
                                                            html.Br(), 
                                                            html.P("Last x Years:"),
                                                            dcc.RadioItems(id="bal_year_picker",
                                                                           options = [5,10,15,20],
                                                                           value=5,
                                                                           inline=True),
                                                    ],width=2),
                                                dbc.Col([
                                                            dcc.Graph(id="bal_first_plot")
                                                    ]),
                                                ])
                                        ]),
                            dcc.Tab(label="Cashflow",
                                    children=[
                                        dbc.Row([
                                            dcc.Markdown(id="tab3_markdown_title",
                                                         style={'textAlign':'center',
                                                                'fontSize':30,
                                                                'fontWeight':'bold',
                                                                'fontFamily':'sans-serif'})
                                                ]),
                                        dbc.Row([
                                                dbc.Col([
                                                            html.P("Select your comparison type :"),
                                                            dcc.RadioItems(id="tab3_OutputPicker",
                                                                           options = ["stock","component"],
                                                                           value="stock"),
                                                            html.P("Select one or more Stocks :"),
                                                            dcc.Dropdown(id="tab3_stock_dropdown",
                                                                        options=cash_df_csv["ticker"].unique(),
                                                                        value="AAPL"),
                                                            html.Br(),          
                                                            html.P("Select a Column to Plot :"),
                                                            dcc.Dropdown(id="tab3_comp_dropdown",
                                                                        options=list(cash_df_csv.select_dtypes(include='number').columns[1:-1]) + calculated_column_names_cash,
                                                                        value="operating_cashflow"),
                                                            html.Br(), 
                                                            html.P("Select plot type :"),
                                                            dcc.RadioItems(id="tab3_graph_picker",
                                                                           options = ["bar","line"],
                                                                           value="bar",
                                                                           inline=True),
                                                            html.Br(), 
                                                            html.P("Last x Years:"),
                                                            dcc.RadioItems(id="tab3_year_picker",
                                                                           options = [5,10,15,20],
                                                                           value=5,
                                                                           inline=True),
                                                            html.P("Report type:"),
                                                            dcc.RadioItems(id="tab3_cash_reporttype",
                                                                           options = ["ANNUAL","QUARTERLY"],
                                                                           value="ANNUAL",
                                                                           inline=True),
                                                    ],width=2),
                                                dbc.Col([
                                                            dcc.Graph(id="tab3_first_plot")
                                                    ]),
                                                ])
                                        ]),
                                    ])
                    ],className="dbc")

@app.callback(
    Output("tab1_stock_dropdown", "multi"),
    Output("tab1_stock_dropdown", "value"),
    Output("tab1_comp_dropdown", "multi"),
    Output("tab1_comp_dropdown", "value"),
    Input("tab1_OutputPicker", "value")
)
def tab1_toggle_dropdown_modes(comparison_type):
    if comparison_type == "stock":
        # Multi-stock selection, single financial structural item
        return True, ["AAPL"], False, "total_revenue"
    else:
        # Single stock selection, multi structural item component layout
        return False, "AAPL", True, ["total_revenue", "net_income"]
    
@app.callback(
    Output("markdown_title","children"),
    Output("first_plot","figure"),#Output("first_plot","children")
    Input("tab1_stock_dropdown","value"),
    Input("tab1_comp_dropdown","value"),
    Input("graph_picker","value"),
    Input("year_picker","value"),
    Input("income_reporttype","value"),
    Input("tab1_OutputPicker","value"),
)
def plot_tab1(tickers,column_name,graph_type,last_x_years,report_type,comparison_type):
    if not tickers:
        raise PreventUpdate
    
    df = (income_df_csv.query(f"report_type == '{report_type}' and ticker in @tickers")
          .sort_values(by=['stock_id','fiscal_date_ending'],ascending=True))
    df = (df
        #.iloc[:last_x_years]
        .assign(calc_net_income = lambda x: x["operating_income"] - x["income_tax_expense"],
                #revenue_growth = lambda x: (x["total_revenue"] - x["total_revenue"].shift(-1))/x["total_revenue"].shift(-1)*100,
                revenue_growth = lambda x: (x["total_revenue"] - x.groupby("ticker")["total_revenue"].shift(-1)) 
                                            / x.groupby("ticker")["total_revenue"].shift(-1) * 100,
                gross_margin = lambda x: x["gross_profit"]/x["total_revenue"] * 100,
                operating_margin = lambda x: x["ebit"]/x["total_revenue"] * 100,
                net_margin = lambda x: (x["operating_income"] - x["income_tax_expense"])/x["total_revenue"] * 100,
                cogs_margin = lambda x: x["cost_of_revenue"]/x["total_revenue"] * 100,
                expense_margin = lambda x: x["operating_expenses"]/x["total_revenue"] * 100,
                tax_margin = lambda x: x["income_tax_expense"]/x["total_revenue"] * 100,
                year_str = lambda x: pd.to_datetime(x["fiscal_date_ending"]).dt.year.astype(str)
                )
        .groupby("ticker").tail(last_x_years if report_type == "ANNUAL" else last_x_years*4)
    )

    blues = ['#F0F8FF', '#D0E1FD', '#A2C2FC', '#6395ED', '#2A52BE', '#1D2951']

    if graph_type == "bar":
        fig = px.bar(df,
                    x= "year_str" if report_type == "ANNUAL" else "fiscal_date_ending",
                    y=column_name,
                    color="ticker" if comparison_type == "stock" else None,
                    title= f"{" ".join(column_name).upper().replace("_"," ")} over the years" if comparison_type == "stock" else f"{", ".join(column_name).upper().replace("_"," ")} over the years" ,
                    hover_name = "fiscal_date_ending",
                    custom_data = ["fiscal_date_ending"],
                    barmode='group',
                    color_discrete_sequence=blues,
                    )

        fig.update_xaxes(
            type="category", 
            tickmode="auto",
            range=None
        )
    else:
        fig = px.line(df, 
                    x="fiscal_date_ending",
                    y=column_name,
                    markers=True,
                    custom_data = ["fiscal_date_ending"],
                    color="ticker",
                    color_discrete_sequence=blues)

        dates = pd.to_datetime(df["fiscal_date_ending"])   
        unique_years = sorted(dates.dt.year.unique())
        clean_ticks = [f"{yr}-01-01" for yr in unique_years]
        fig.update_xaxes(type="date",
                        tickmode="array",
                        tickvals=clean_ticks,
                        tickformat="%Y",
                        range=[dates.min() - pd.DateOffset(months=6), dates.max() + pd.DateOffset(months=6)])

    fig.update_layout(
        template=template_name,
        xaxis_title="Fiscal Year",
        #yaxis_title=column_name.replace("_", " ").title(),
        bargap=0.2,
        bargroupgap=0.05,
        margin=dict(l=40, r=40, t=60, b=40)
    )

    title =  "**NO TITLE**"
    return title,fig

@app.callback(
    Output("second_plot","figure"),
    #Output("debug_md","children"),
    Input("first_plot","hoverData"),
    Input("tab1_stock_dropdown","value"),
    Input("income_reporttype","value"),
)
def plot_tab11(hoverData,tickers,report_type):
    # 1. Broad safety catch for missing or empty hover data
    if not hoverData or "points" not in hoverData or not tickers:
        raise PreventUpdate
    point = hoverData["points"][0]
    custom_data = point.get("customdata")
    
    # 2. Crash protection: Exit early if customdata isn't populated yet
    if custom_data is None:
        raise PreventUpdate
      
    #df = income_df_csv.query(f"report_type == '{report_type}' and ticker in @tickers")

    df = (income_df_csv.query(f"report_type == '{report_type}' and ticker in @tickers")
          .sort_values(by=['stock_id','fiscal_date_ending'],ascending=True))
    df = (df
        .assign(calc_net_income = lambda x: x["operating_income"] - x["income_tax_expense"],
                revenue_growth = lambda x: (x["total_revenue"] - x.groupby("ticker")["total_revenue"].shift(-1)) 
                                            / x.groupby("ticker")["total_revenue"].shift(-1) * 100,
                gross_margin = lambda x: x["gross_profit"]/x["total_revenue"] * 100,
                operating_margin = lambda x: x["ebit"]/x["total_revenue"] * 100,
                net_margin = lambda x: (x["operating_income"] - x["income_tax_expense"])/x["total_revenue"] * 100,
                cogs_margin = lambda x: x["cost_of_revenue"]/x["total_revenue"] * 100,
                expense_margin = lambda x: x["operating_expenses"]/x["total_revenue"] * 100,
                tax_margin = lambda x: x["income_tax_expense"]/x["total_revenue"] * 100
                )
        .astype({"fiscal_date_ending":"datetime64[ns]"})
        )
    year = pd.to_datetime(hoverData["points"][0]["customdata"][0])
    plot_df = (
                pd.DataFrame(df[df.fiscal_date_ending == year][["cost_of_revenue","operating_expenses","income_tax_expense","calc_net_income"]].T)
                .reset_index()
            )

    if plot_df.shape[1] != 2:
        raise PreventUpdate
    
    plot_df.columns = ["col1", "col2"]
    #plot_df.sort_values(by="col2",inplace=True,ascending=False)
    fig = px.pie(plot_df, values="col2", names="col1", color = "col1",title='Revenue Composition',hole=0.25,
                              color_discrete_map={  'cost_of_revenue':'navyblue',
                                                    'operating_expenses':'cyan',
                                                    'income_tax_expense':'royalblue',
                                                    'calc_net_income':'darkblue'})
    fig.update_traces(sort=False, selector=dict(type='pie'),direction="clockwise")

    return fig#,f"selected fiscal year is {year}"

@app.callback(
    Output("tab2_stock_dropdown", "multi"),
    Output("tab2_stock_dropdown", "value"),
    Output("tab2_comp_dropdown", "multi"),
    Output("tab2_comp_dropdown", "value"),
    Input("tab2_OutputPicker", "value")
)
def tab2_toggle_dropdown_modes(comparison_type):
    if comparison_type == "stock":
        # Multi-stock selection, single financial structural item
        return True, ["AAPL"], False, "total_current_assets"
    else:
        # Single stock selection, multi structural item component layout
        return False, "AAPL", True, ["total_current_assets", "total_current_liabilities"]


@app.callback(
    Output("bal_markdown_title","children"),
    Output("bal_first_plot","figure"),
    Input("tab2_stock_dropdown","value"),
    Input("tab2_comp_dropdown","value"),
    Input("bal_graph_picker","value"),
    Input("bal_year_picker","value"),
    Input("tab2_OutputPicker","value"),
)
def plot_tab2(tickers,column_name,graph_type,last_x_years,comparison_type):
    if not tickers or not column_name or not graph_type or not last_x_years or not comparison_type:
        raise PreventUpdate
    
    df = bal_df_csv.query(f"report_type == 'ANNUAL' and ticker in @tickers")
    df = (df
            .assign(current_ratio = lambda x: x["total_current_assets"]/x["total_current_liabilities"],
                    liabilities_to_equity = lambda x: x["total_liabilities"]/x["total_shareholder_equity"],
                    return_on_equity = lambda x: income_df_csv["net_income"]/x["total_shareholder_equity"] *100,
                    year_str = lambda x: pd.to_datetime(x["fiscal_date_ending"]).dt.year.astype(str)
                    )  
            .groupby("ticker").head(last_x_years)
    )

    df = df.sort_values("year_str")

    blues = ['#D6E4FF', '#A9C7FF', '#7DA6FF', '#4A7FFF', '#1D4ED8', '#1E3A8A']

    if graph_type == "bar":
        fig = px.bar(df,
                    x="fiscal_date_ending",
                    y=column_name,
                    color= "ticker" if comparison_type == "stock" else None,
                    title= f"{" ".join(column_name).upper().replace("_"," ")} over the years" if comparison_type == "stock" else f"{", ".join(column_name).upper().replace("_"," ")} over the years" ,
                    hover_name = "fiscal_date_ending",
                    custom_data = ["fiscal_date_ending"],
                    barmode='group',
                    color_discrete_sequence=blues,
                    )

        fig.update_xaxes(
            type="category", 
            tickmode="auto",
            range=None
        )
    else:
        fig = px.line(df, 
                    x='fiscal_date_ending',
                    y=column_name,
                    #markers=True,
                    custom_data = ["fiscal_date_ending"],
                    color="ticker" if comparison_type == "stock" else None,
                    title=f"{" ".join(column_name).upper().replace("_"," ")} over the years" if comparison_type == "stock" else f"{", ".join(column_name).upper().replace("_"," ")} over the years" ,
                    color_discrete_sequence=blues)

        dates = pd.to_datetime(df["fiscal_date_ending"])   
        unique_years = sorted(dates.dt.year.unique())
        clean_ticks = [f"{yr}-01-01" for yr in unique_years]
        fig.update_xaxes(type="date",
                        tickmode="array",
                        tickvals=clean_ticks,
                        tickformat="%Y",
                        range=[dates.min() - pd.DateOffset(months=6), dates.max() + pd.DateOffset(months=6)])

    fig.update_layout(
        template=template_name,
        xaxis_title="Fiscal Year",
        #yaxis_title=column_name.replace("_", " ").title(),
        bargap=0.2,
        bargroupgap=0.05,
        margin=dict(l=40, r=40, t=60, b=40)
    )

    title =  "**NO TITLE**"
    return title,fig

@app.callback(
    Output("tab3_stock_dropdown", "multi"),
    Output("tab3_stock_dropdown", "value"),
    Output("tab3_comp_dropdown", "multi"),
    Output("tab3_comp_dropdown", "value"),
    Input("tab3_OutputPicker", "value")
)
def tab3_toggle_dropdown_modes(comparison_type):
    if comparison_type == "stock":
        # Multi-stock selection, single financial structural item
        return True, ["AAPL"], False, "operating_cashflow"
    else:
        # Single stock selection, multi structural item component layout
        return False, "AAPL", True, ["operating_cashflow", "free_cash_flow"]
    
@app.callback(
    Output("tab3_markdown_title","children"),
    Output("tab3_first_plot","figure"),
    Input("tab3_stock_dropdown","value"),
    Input("tab3_comp_dropdown","value"),
    Input("tab3_graph_picker","value"),
    Input("tab3_year_picker","value"),
    Input("tab3_cash_reporttype","value"),
    Input("tab3_OutputPicker", "value")
)
def plot_tab3(tickers,column_name,graph_type,last_x_years,report_type,comparison_type):
    if not tickers:
        raise PreventUpdate
    
    df = (cash_df_csv.query(f"report_type == '{report_type}' and ticker in @tickers")
          .sort_values(by=['stock_id','fiscal_date_ending'],ascending=True))
    df = (df
        .assign(free_cash_flow = lambda x: x["operating_cashflow"] - x["capital_expenditures"],
                year_str = lambda x: pd.to_datetime(x["fiscal_date_ending"]).dt.year.astype(str))
        .groupby("ticker").tail(last_x_years if report_type == "ANNUAL" else last_x_years*4)
    )

    blues = ['#F0F8FF', '#D0E1FD', '#A2C2FC', '#6395ED', '#2A52BE', '#1D2951']

    if graph_type == "bar":
        fig = px.bar(df,
                    x= "year_str" if report_type == "ANNUAL" else "fiscal_date_ending",
                    y=column_name,
                    color="ticker" if comparison_type == "stock" else None,
                    title=f"{" ".join(column_name).upper().replace("_"," ")} over the years" if comparison_type == "stock" else f"{", ".join(column_name).upper().replace("_"," ")} over the years" ,
                    hover_name = "fiscal_date_ending",
                    custom_data = ["fiscal_date_ending"],
                    barmode='group',
                    color_discrete_sequence=blues,
                    )

        fig.update_xaxes(
            type="category", 
            tickmode="auto",
            range=None
        )
    else:
        fig = px.line(df, 
                    x="fiscal_date_ending",
                    y=column_name,
                    markers=True,
                    custom_data = ["fiscal_date_ending"],
                    color="ticker" if comparison_type == "stock" else None,
                    color_discrete_sequence=blues,
                    title=f"{" ".join(column_name).upper().replace("_"," ")} over the years" if comparison_type == "stock" else f"{", ".join(column_name).upper().replace("_"," ")} over the years",
                    )

        dates = pd.to_datetime(df["fiscal_date_ending"])   
        unique_years = sorted(dates.dt.year.unique())
        clean_ticks = [f"{yr}-01-01" for yr in unique_years]
        fig.update_xaxes(type="date",
                        tickmode="array",
                        tickvals=clean_ticks,
                        tickformat="%Y",
                        range=[dates.min() - pd.DateOffset(months=6), dates.max() + pd.DateOffset(months=6)])

    fig.update_layout(
        template=template_name,
        xaxis_title="Fiscal Year",
        #yaxis_title=column_name.replace("_", " ").title(),
        bargap=0.2,
        bargroupgap=0.05,
        margin=dict(l=40, r=40, t=60, b=40)
    )

    title =  "**NO TITLE**"
    return title,fig

if __name__ == "__main__":
    app.run(debug=True,jupyter_mode="external")

Dash app running on http://127.0.0.1:8050/