In [1]:
from dash import Dash, dcc, html, dash_table
import dash_bootstrap_components as dbc
from dash.dependencies import Output, Input
from dash.exceptions import PreventUpdate
from dash_bootstrap_templates import load_figure_template
import plotly.express as px
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from sqlalchemy import create_engine, MetaData,Table,Column, Integer, String,text,select
from sqlalchemy.orm import Session
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy import and_
from sqlalchemy import func,desc,asc
from sqlalchemy import cast, Numeric,Float
import urllib.parse

In [3]:
with open("../querying_using_sqlalchemy/db_password.txt") as file:
    db_pw = file.read()

db_pw = db_pw.strip()

encoded_pw = urllib.parse.quote_plus(db_pw)
url = f"postgresql://postgres:{encoded_pw}@localhost:5432/postgres"
engine = create_engine(url)

In [7]:
# declarative base class
class Base(DeclarativeBase):
    pass

# Load the "Parent" first
class BalanceSheetTable(Base):
    __tablename__ = "balance_sheet"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

# Then load the "Children"
class IncomeStatementTable(Base):
    __tablename__ = "income_statement"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class CashFlowTable(Base):
    __tablename__ = "cash_flow"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class SharesOutstanding(Base):
    __tablename__ = "shares_outstanding"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Splits(Base):
    __tablename__ = "splits"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Dividends(Base):
    __tablename__ = "dividends"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Earnings(Base):
    __tablename__ = "earnings"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class EarningsEstimates(Base):
    __tablename__ = "earnings_estimates"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Overview(Base):
    __tablename__ = "overview"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Stock(Base):
    __tablename__ = "stock"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class Currency(Base):
    __tablename__ = "currency"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

class OHLCV(Base):
    __tablename__ = "ohlcv"
    __table_args__ = {"autoload_with": engine, "schema": "alpha_vantage_db"}

In [25]:
from abc import ABC, abstractmethod
class Loader(ABC):
    stock_table = Stock
    @abstractmethod
    def get_data(self):
        pass

class DatabaseLoader(Loader):
    def get_data(self,table):
        stmt = (
                select(table,self.stock_table)
                .join(
                    self.stock_table, 
                    and_(
                        table.stock_id == self.stock_table.stock_id
                )))
        result = pd.read_sql(stmt, engine)
        return result

class CSVLoader(Loader):
    def get_data(self,csvname):
        result = pd.read_csv(csvname)
        return result

In [44]:
class FinanceStatement:
    def __init__(self,data_loader = None):
        self.df = pd.DataFrame()
        self.data_loader = data_loader

    def set_loading_type(self,data_loader):
        self.data_loader = data_loader

    def perform_load(self,table_or_csv):
        self.df = self.data_loader.get_data(table_or_csv)  

    def write_csv(self,csvname):
        return self.df.to_csv(csvname,index=False)
    
    def get_numeric_columns(self):
        return self.df.select_dtypes(include='number').columns[1:-1]

    def get_unique_ticker(self):
        return self.df["ticker"].unique()
    
class IncomeStatement(FinanceStatement):
    pass

class BalanceSheet(FinanceStatement):
    pass

class CashFlowStatement(FinanceStatement):
    pass

In [45]:
income_statement = IncomeStatement(data_loader=DatabaseLoader())
income_statement.perform_load(table_or_csv=IncomeStatementTable)

In [46]:
income_statement.df

,stock_id,fiscal_date_ending,reported_currency,gross_profit,total_revenue,cost_of_revenue,cost_of_goods_and_services_sold,operating_income,selling_general_and_administrative,research_and_development,...,income_tax_expense,interest_and_debt_expense,net_income_from_continuing_operations,comprehensive_income_net_of_tax,ebit,ebitda,net_income,report_type,stock_id_1,ticker
0,1,2025-09-30,USD,1.952010e+11,4.161610e+11,2.209600e+11,2.209600e+11,1.330500e+11,8.077000e+09,3.455000e+10,...,2.071900e+10,None,1.120100e+11,None,1.327290e+11,1.444270e+11,1.120100e+11,ANNUAL,1,AAPL
1,1,2024-09-30,USD,1.806830e+11,3.910350e+11,2.103520e+11,2.103520e+11,1.232160e+11,2.609700e+10,3.137000e+10,...,2.974900e+10,None,9.373600e+10,None,1.232160e+11,1.346610e+11,9.373600e+10,ANNUAL,1,AAPL
2,1,2023-09-30,USD,1.691480e+11,3.832850e+11,2.141370e+11,2.141370e+11,1.143010e+11,2.493200e+10,2.991500e+10,...,1.674100e+10,None,9.699500e+10,None,1.143010e+11,1.258200e+11,9.699500e+10,ANNUAL,1,AAPL
3,1,2022-09-30,USD,1.707820e+11,3.943280e+11,2.235460e+11,2.235460e+11,1.194370e+11,2.509400e+10,2.625100e+10,...,1.930000e+10,None,9.980300e+10,None,1.194370e+11,1.305410e+11,9.980300e+10,ANNUAL,1,AAPL
4,1,2021-09-30,USD,1.528360e+11,3.658170e+11,2.129810e+11,2.129810e+11,1.089490e+11,2.197300e+10,2.191400e+10,...,1.452700e+10,None,9.468000e+10,None,1.118520e+11,1.231360e+11,9.468000e+10,ANNUAL,1,AAPL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9953,3,2010-06-30,USD,5.008900e+10,6.248400e+10,1.239500e+10,1.239500e+10,2.409800e+10,4.063000e+09,8.714000e+09,...,6.253000e+09,None,1.876000e+10,None,2.516400e+10,2.783700e+10,1.876000e+10,ANNUAL,3,MSFT
9954,3,2009-06-30,USD,4.628200e+10,5.843700e+10,1.215500e+10,1.215500e+10,2.036300e+10,4.030000e+09,9.010000e+09,...,5.252000e+09,None,NaN,None,1.985900e+10,2.242100e+10,1.456900e+10,ANNUAL,3,MSFT
9955,3,2008-06-30,USD,4.882200e+10,6.042000e+10,1.159800e+10,1.159800e+10,2.227100e+10,5.127000e+09,8.164000e+09,...,6.133000e+09,None,NaN,None,2.392000e+10,2.597600e+10,1.768100e+10,ANNUAL,3,MSFT
9956,3,2007-06-30,USD,4.042900e+10,5.112200e+10,1.069300e+10,1.069300e+10,1.843800e+10,3.329000e+09,7.121000e+09,...,6.036000e+09,None,NaN,None,1.843800e+10,1.987800e+10,1.406500e+10,ANNUAL,3,MSFT
9957,3,2006-06-30,USD,3.663200e+10,4.428200e+10,7.650000e+09,7.650000e+09,1.647200e+10,3.758000e+09,6.584000e+09,...,5.663000e+09,None,NaN,None,1.647200e+10,1.737500e+10,1.259900e+10,ANNUAL,3,MSFT

In [47]:
balance_sheet = BalanceSheet(data_loader=DatabaseLoader())
balance_sheet.perform_load(table_or_csv=BalanceSheetTable)

In [48]:
balance_sheet.df

,stock_id,fiscal_date_ending,reported_currency,total_assets,total_current_assets,cash_and_cash_equivalents_at_carrying_value,cash_and_short_term_investments,inventory,current_net_receivables,total_non_current_assets,...,other_current_liabilities,other_non_current_liabilities,total_shareholder_equity,treasury_stock,retained_earnings,common_stock,common_stock_shares_outstanding,report_type,stock_id_1,ticker
0,1,2025-09-30,USD,3.592410e+11,1.479570e+11,3.593400e+10,3.593400e+10,5.718000e+09,7.295700e+10,2.112840e+11,...,6.427000e+10,4.154900e+10,7.373300e+10,NaN,-1.426400e+10,9.356800e+10,1.500470e+10,ANNUAL,1,AAPL
1,1,2024-09-30,USD,3.649800e+11,1.529870e+11,2.994300e+10,2.994300e+10,7.286000e+09,6.624300e+10,2.119930e+11,...,5.007100e+10,3.663400e+10,5.695000e+10,NaN,-1.915400e+10,8.327600e+10,1.540810e+10,ANNUAL,1,AAPL
2,1,2023-09-30,USD,3.525830e+11,1.435660e+11,2.996500e+10,2.996500e+10,6.331000e+09,2.950800e+10,2.090170e+11,...,5.882900e+10,4.984800e+10,6.214600e+10,NaN,-2.140000e+08,7.381200e+10,1.581255e+10,ANNUAL,1,AAPL
3,1,2022-09-30,USD,3.527550e+11,1.354050e+11,2.364600e+10,2.364600e+10,4.946000e+09,2.818400e+10,2.173500e+11,...,6.084500e+10,4.914200e+10,5.067200e+10,NaN,-3.068000e+09,6.484900e+10,1.632582e+10,ANNUAL,1,AAPL
4,1,2021-09-30,USD,3.510020e+11,1.348360e+11,3.494000e+10,3.494000e+10,6.580000e+09,2.627800e+10,2.161660e+11,...,4.749300e+10,2.863600e+10,6.309000e+10,NaN,5.562000e+09,5.736500e+10,1.686492e+10,ANNUAL,1,AAPL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10020,3,2017-06-30,USD,2.410860e+11,1.598510e+11,7.663000e+09,7.663000e+09,2.181000e+09,1.979200e+10,8.123500e+10,...,1.291400e+10,1.718400e+10,7.239400e+10,0.0,2.648000e+09,6.931500e+10,7.832000e+09,ANNUAL,3,MSFT
10021,3,2015-06-30,USD,1.744720e+11,1.227970e+11,5.595000e+09,5.595000e+09,2.902000e+09,1.790800e+10,5.167500e+10,...,1.174300e+10,1.354400e+10,8.008300e+10,0.0,9.096000e+09,6.846500e+10,8.254000e+09,ANNUAL,3,MSFT
10022,3,2014-06-30,USD,1.723840e+11,1.142460e+11,8.669000e+09,8.669000e+09,2.660000e+09,1.954400e+10,5.813800e+10,...,1.226100e+10,1.159400e+10,8.978400e+10,0.0,1.771000e+10,6.836600e+10,8.399000e+09,ANNUAL,3,MSFT
10023,3,2013-06-30,USD,1.424310e+11,1.014660e+11,3.804000e+09,3.804000e+09,1.938000e+09,1.748600e+10,4.096500e+10,...,8.359000e+09,1.000000e+10,7.894400e+10,0.0,9.895000e+09,6.730600e+10,8.470000e+09,ANNUAL,3,MSFT
10024,3,2012-06-30,USD,1.212710e+11,8.508400e+10,6.938000e+09,6.938000e+09,1.137000e+09,1.578000e+10,3.618700e+10,...,7.840000e+09,8.208000e+09,6.636300e+10,0.0,5.660000e+08,6.579700e+10,8.506000e+09,ANNUAL,3,MSFT

In [49]:
cashflow = CashFlowStatement(data_loader=DatabaseLoader())
cashflow.perform_load(table_or_csv=CashFlowTable)

In [50]:
cashflow.df

,stock_id,fiscal_date_ending,reported_currency,operating_cashflow,payments_for_operating_activities,proceeds_from_operating_activities,change_in_operating_liabilities,change_in_operating_assets,depreciation_depletion_and_amortization,capital_expenditures,...,proceeds_from_issuance_of_preferred_stock,proceeds_from_repurchase_of_equity,proceeds_from_sale_of_treasury_stock,stock_based_compensation,change_in_cash_and_cash_equivalents,change_in_exchange_rate,net_income,report_type,stock_id_1,ticker
0,1,2025-09-30,USD,1.114820e+11,None,None,None,None,1.169800e+10,1.271500e+10,...,None,-9.071100e+10,None,1.286300e+10,NaN,NaN,1.120100e+11,ANNUAL,1,AAPL
1,1,2024-09-30,USD,1.182540e+11,None,None,None,None,1.144500e+10,9.447000e+09,...,None,-9.494900e+10,None,1.168800e+10,NaN,NaN,9.373600e+10,ANNUAL,1,AAPL
2,1,2023-09-30,USD,1.105430e+11,None,None,None,None,1.151900e+10,1.095900e+10,...,None,-7.755000e+10,None,1.083300e+10,5.760000e+09,NaN,9.699500e+10,ANNUAL,1,AAPL
3,1,2022-09-30,USD,1.221510e+11,None,None,None,None,1.110400e+10,1.070800e+10,...,None,-8.940200e+10,None,9.038000e+09,-1.095200e+10,NaN,9.980300e+10,ANNUAL,1,AAPL
4,1,2021-09-30,USD,1.040380e+11,None,None,None,None,1.128400e+10,1.108500e+10,...,None,-8.597100e+10,None,7.906000e+09,-3.860000e+09,NaN,9.468000e+10,ANNUAL,1,AAPL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9951,2,2006-12-31,USD,-3.428000e+06,None,None,None,None,6.150000e+05,6.505000e+06,...,None,NaN,None,NaN,NaN,NaN,-2.995700e+07,ANNUAL,2,TSLA
9952,3,2009-06-30,USD,1.903700e+10,None,None,None,None,2.562000e+09,3.119000e+09,...,None,-9.353000e+09,None,1.708000e+09,NaN,NaN,1.456900e+10,ANNUAL,3,MSFT
9953,3,2008-06-30,USD,2.161200e+10,None,None,None,None,2.056000e+09,3.182000e+09,...,None,-1.253300e+10,None,1.479000e+09,NaN,NaN,1.768100e+10,ANNUAL,3,MSFT
9954,3,2007-06-30,USD,1.779600e+10,None,None,None,None,1.440000e+09,2.264000e+09,...,None,-2.757500e+10,None,-2.920000e+08,NaN,NaN,1.406500e+10,ANNUAL,3,MSFT
9955,3,2006-06-30,USD,1.440400e+10,None,None,None,None,9.030000e+08,1.578000e+09,...,None,-1.920700e+10,None,1.454000e+09,NaN,NaN,1.259900e+10,ANNUAL,3,MSFT